import { personalMonth, personalPosition, businessMonth, breakEven as calcBreakEven, simulateBusiness } from './financial-engine.js';
import * as cloud from './supabase-store.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={mode:localStorage.getItem('feo-mode')||'personal',section:'home',theme:localStorage.getItem('feo-theme')||'light'};
const money=(n,c='USD')=>new Intl.NumberFormat('es-ES',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const moneyMinor=(n,c='USD')=>new Intl.NumberFormat('es-ES',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format((n||0)/100);
const toMinor=s=>{const v=String(s??'').trim().replace(',','.');if(!/^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/.test(v))return null;const [a,b='']=v.split('.');const n=Number(a)*100+Number((b+'00').slice(0,2));return Number.isSafeInteger(n)?n:null};
const navs={personal:[['home','⌂','Inicio'],['income','＋','Ingresos'],['expenses','−','Gastos'],['debts','◫','Deudas'],['savings','◇','Ahorros'],['goals','◎','Metas'],['assets','▣','Activos'],['diagnostic','✦','Diagnóstico']],business:[['home','⌂','Inicio'],['sales','＋','Ventas'],['costs','−','Costos'],['expenses','▤','Gastos'],['cashflow','↕','Flujo de caja'],['breakEven','◎','Punto de equilibrio'],['decisions','✦','Decisiones'],['results','▣','Resultado']]};
const personal={income:4850,expenses:3120,savings:650,debt:350,assets:18400,totalDebt:6200};
const business={sales:12500,collections:10800,costs:4300,expenses:3100,debtPayments:650,cash:6420};
document.documentElement.dataset.theme=state.theme;
function renderNav(){const items=navs[state.mode];$('#nav').innerHTML=items.map(([id,ic,t])=>`<button data-section="${id}" class="${state.section===id?'active':''}"><b>${ic}</b><span>${t}</span></button>`).join('');$('#mobileNav').innerHTML=[items[0],items[1],state.mode==='business'?items[6]:items[5],['settings','⚙','Ajustes'],['profile','○','Perfil']].map(([id,ic,t])=>`<button data-section="${id}" class="${state.section===id?'active':''}"><i>${ic}</i>${t}</button>`).join('');bindNav()}
function bindNav(){$$('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;render()})}
function bars(){return [48,64,55,78,69,88,74].map((h,i)=>`<div class="bar ${i===5?'active':''}" style="height:${h}%"><span>${['Mar','Abr','May','Jun','Jul','Ago','Sep'][i]}</span></div>`).join('')}
function monthKey(){return '2026-09'}
function asMinor(x){return Number.isSafeInteger(x?.amountMinor)?x.amountMinor:0}
function personalEngineData(){const b=records.personal||{};return {income:(b.income||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),expense:(b.expense||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),saving:(b.saving||[]).map(x=>({date:x.date,amountMinor:asMinor(x),direction:x.direction||'deposit'})),debtPayments:(b.debtPayment||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),assets:(b.asset||[]).map((x,i)=>({id:x.id||`asset-${i}`,date:x.date,valueMinor:asMinor(x)})),debts:(b.debt||[]).map((x,i)=>({id:x.id||`debt-${i}`,date:x.date,balanceMinor:asMinor(x)}))}}
function businessEngineData(){const b=records.business||{};return {sales:(b.sale||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),collections:(b.collection||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),variableCosts:(b.cost||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),operatingExpenses:(b.expense||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),cashPayments:(b.cashPayment||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),debtPrincipalPayments:(b.debtPrincipal||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),debtInterestPayments:(b.debtInterest||[]).map(x=>({date:x.date,amountMinor:asMinor(x)}))}}
function home(){if(state.mode==='personal'){const m=personalMonth(personalEngineData(),monthKey()),pos=personalPosition(personalEngineData(),'2026-09-30');return `<div class="hero"><div class="heroTop"><div><small>Disponible este mes</small><h2>${moneyMinor(m.available,currency())}</h2><div class="delta">Calculado con tus registros de septiembre</div></div><button class="info" data-info="available">i</button></div><div class="heroActions"><button class="light" data-section="income">＋ Ingreso</button><button data-section="expenses">− Gasto</button><button data-section="savings">◇ Ahorrar</button><button data-section="debts">◫ Deuda</button></div></div><div class="kpis"><div class="kpi"><small>Ingresos</small><strong>${moneyMinor(m.income,currency())}</strong><em>Registros del mes</em></div><div class="kpi"><small>Gastos</small><strong>${moneyMinor(m.expense,currency())}</strong><em>${m.income?Math.round(m.expense*100/m.income):0}% de ingresos</em></div><div class="kpi"><small>Ahorro neto</small><strong>${moneyMinor(m.netSavings,currency())}</strong><em>${m.savingsRateBp==null?'Sin ingresos':(m.savingsRateBp/100).toFixed(1)+'%'}</em></div><div class="kpi"><small>Patrimonio</small><strong>${moneyMinor(pos.netWorth,currency())}</strong><em>Activos − deudas</em></div></div><div class="grid"><div class="card"><h3>Tu posición</h3><div class="list"><div class="row"><div><b>Activos</b></div><div class="amount">${moneyMinor(pos.assets,currency())}</div></div><div class="row"><div><b>Deudas pendientes</b></div><div class="amount">${moneyMinor(pos.debts,currency())}</div></div><div class="row"><div><b>Pagos de deuda del mes</b></div><div class="amount">${moneyMinor(m.debtPayments,currency())}</div></div></div></div><div class="card focus"><span class="focusTag">LECTURA DEL MES</span><h2>${m.available>=0?'Tu mes mantiene disponible positivo':'Tus salidas superan tus entradas'}</h2><p class="sub">${m.available>=0?'Después de gastos, ahorro y pagos de deuda todavía conservas disponible.':'Revisa gastos, ahorro programado y pagos de deuda antes de asumir nuevos compromisos.'}</p></div></div>`}return businessHome()}
function businessHome(){const m=businessMonth(businessEngineData(),monthKey());const margin=m.sales?Math.round(m.operatingResult*1000/m.sales)/10:null;return `<div class="hero"><div class="heroTop"><div><small>Flujo de caja del mes</small><h2>${moneyMinor(m.cashFlow,currency())}</h2><div class="delta">Cobros reales − pagos reales − deuda</div></div><button class="info" data-info="cash">i</button></div><div class="heroActions"><button class="light" data-section="sales">＋ Venta</button><button data-section="costs">− Costo</button><button data-section="cashflow">↕ Cobro/Pago</button><button data-section="decisions">✦ Simular decisión</button></div></div><div class="kpis"><div class="kpi"><small>Ventas</small><strong>${moneyMinor(m.sales,currency())}</strong><em>No implica cobro</em></div><div class="kpi"><small>Resultado</small><strong>${moneyMinor(m.operatingResult,currency())}</strong><em>${margin==null?'Sin ventas':margin+'% sobre ventas'}</em></div><div class="kpi"><small>Cobros</small><strong>${moneyMinor(m.collections,currency())}</strong><em>Caja efectivamente recibida</em></div><div class="kpi"><small>Flujo de caja</small><strong>${moneyMinor(m.cashFlow,currency())}</strong><em>Independiente del resultado</em></div></div><div class="grid"><div class="card"><h3>Resultado vs. caja</h3><div class="list"><div class="row"><div><b>Resultado operativo</b><small>Ventas − costes − gastos − intereses</small></div><div class="amount">${moneyMinor(m.operatingResult,currency())}</div></div><div class="row"><div><b>Flujo de caja</b><small>Cobros − pagos − principal − intereses</small></div><div class="amount">${moneyMinor(m.cashFlow,currency())}</div></div></div></div><div class="card focus"><span class="focusTag">CONTROL FINANCIERO</span><h2>${m.sales>0&&m.collections===0?'Tienes ventas, pero ningún cobro registrado':'Ventas y caja se miden por separado'}</h2><p class="sub">Una venta no se convierte automáticamente en efectivo. Registra cobros y pagos en Flujo de caja.</p></div></div>`}
const titles={income:'Ingresos',expenses:'Gastos',debts:'Deudas',savings:'Ahorros',goals:'Metas',assets:'Activos',diagnostic:'Diagnóstico financiero',sales:'Ventas',costs:'Costos',cashflow:'Flujo de caja',breakEven:'Punto de equilibrio',decisions:'Motor de Decisiones',results:'Resultado',profile:'Mi perfil',settings:'Ajustes'};
function genericLegacy(){const t=titles[state.section]||'Finanzas'; if(state.section==='decisions')return decisions(); if(state.section==='profile')return profile(); if(state.section==='settings')return settings(); if(state.section==='breakEven')return breakEven();return `<div class="sectionHead"><div><h2>${t}</h2><p>${state.mode==='personal'?'Gestiona tus finanzas personales con claridad.':'Mide lo que ocurre realmente en tu negocio.'}</p></div><button class="primary">＋ Nuevo registro</button></div><div class="grid"><div class="card"><h3>${t} · Septiembre</h3><p class="sub">Vista del período seleccionado</p><div class="chart">${bars()}</div></div><div class="card focus"><span class="focusTag">INTERPRETACIÓN</span><h2>Entiende antes de actuar</h2><p class="sub">Los datos de esta sección alimentan tu diagnóstico y las recomendaciones del sistema.</p><button class="info" data-info="generic" style="margin-top:16px">i</button></div></div>`}
function decisions(){const m=businessMonth(businessEngineData(),monthKey());return `<div class="sectionHead"><div><h2>Motor de Decisiones</h2><p>Prueba una decisión antes de llevarla a tu negocio real.</p></div><button class="info" data-info="decisions">i</button></div><div class="card"><h3>¿Qué quieres evaluar?</h3><div class="decisionGrid"><div class="decision" data-sim="price"><span>↗</span><b>Cambiar precios</b><small>Evalúa margen, resultado y equilibrio.</small></div><div class="decision" data-sim="hire"><span>＋</span><b>Contratar</b><small>Mide el impacto de 800/mes de coste fijo.</small></div><div class="decision" data-sim="sales"><span>◎</span><b>Cambio en ventas</b><small>Simula un escenario adverso de -10%.</small></div></div></div><div class="grid"><div class="card"><h3>Situación actual</h3><div class="list"><div class="row"><div><b>Ventas</b></div><div class="amount">${moneyMinor(m.sales,currency())}</div></div><div class="row"><div><b>Resultado</b></div><div class="amount">${moneyMinor(m.operatingResult,currency())}</div></div><div class="row"><div><b>Flujo de caja</b></div><div class="amount">${moneyMinor(m.cashFlow,currency())}</div></div></div></div><div class="card focus"><span class="focusTag">REGLA IMPORTANTE</span><h2>Una simulación no cambia tus datos</h2><p class="sub">Los escenarios sirven para decidir. No son predicciones y solo usan los supuestos mostrados.</p></div></div>`}
function breakEven(){return `<div class="sectionHead"><div><h2>Punto de equilibrio</h2><p>Cuánto necesitas vender para cubrir tus costes y gastos.</p></div><button class="info" data-info="breakeven">i</button></div><div class="hero"><small>Punto de equilibrio mensual</small><h2>${money(8260)}</h2><div class="delta">Tus ventas actuales están ${money(4240)} por encima</div></div><div class="grid"><div class="card"><h3>Lectura rápida</h3><p class="sub">Por encima de ${money(8260)} empiezas a generar resultado positivo bajo la estructura actual.</p></div><div class="card focus"><span class="focusTag">¿QUÉ PASA SI...?</span><h2>Prueba una decisión</h2><p class="sub">Una contratación, un aumento de alquiler o un cambio de precio mueve tu punto de equilibrio.</p><button class="primary" data-section="decisions" style="margin-top:16px">Abrir simulador</button></div></div>`}
function profileLegacy(){return `<div class="sectionHead"><div><h2>Mi perfil</h2><p>Tu identidad y preferencias financieras.</p></div></div><div class="grid"><div class="card"><div class="profileCard"><div class="profilePhoto">AZ</div><div><h2 style="margin:0">Alejandro Zambrano</h2><p class="sub">Cuenta principal</p><button class="ghost" style="margin-top:10px">Cambiar foto</button></div></div></div><div class="card"><div class="formGrid"><div class="field"><label>Nombre</label><input value="Alejandro Zambrano"></div><div class="field"><label>Correo</label><input value="usuario@ejemplo.com"></div><div class="field"><label>País</label><select><option>Ecuador</option><option>España</option></select></div><div class="field"><label>Moneda personal</label><select><option>USD — Dólar</option><option>EUR — Euro</option></select></div></div></div></div>`}
function settingsLegacy(){return `<div class="sectionHead"><div><h2>Ajustes</h2><p>Personaliza la experiencia y controla los datos de prueba.</p></div></div><div class="grid"><div class="card"><h3>Apariencia</h3><div class="settingsRow"><div><b>Modo de color</b><small>Claro, oscuro o según tu dispositivo.</small></div><button class="ghost" id="settingTheme">${state.theme==='dark'?'Oscuro':'Claro'}</button></div><div class="settingsRow"><div><b>Recorrido inicial</b><small>Puedes volver a ver el tutorial cuando quieras.</small></div><button class="ghost" id="restartTour">Ver recorrido</button></div></div><div class="card"><h3>Datos de demostración</h3><div class="settingsRow"><div><b>Personal</b><small>12 meses de datos de ejemplo certificados.</small></div><button class="ghost">Cargar / eliminar</button></div><div class="settingsRow"><div><b>Negocio</b><small>24 meses para explorar resultados y decisiones.</small></div><button class="ghost">Cargar / eliminar</button></div><p class="sub" style="margin-top:14px">Los datos demo se identifican por separado y nunca deben borrar datos reales.</p></div></div>`}
function render(){renderNav();$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('#pageTitle').textContent=state.section==='home'?(state.mode==='personal'?'Hola, Alejandro':'Tu negocio, hoy'):titles[state.section]||'Finanzas en Orden';$('#content').innerHTML=state.section==='home'?home():generic();bindNav();bindExtras()}
function bindExtrasLegacy(){$$('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info));$$('[data-sim]').forEach(b=>b.onclick=()=>showSim(b.dataset.sim));$('#restartTour')?.addEventListener('click',()=>startTour(true));$('#settingTheme')?.addEventListener('click',toggleTheme)}
function showInfo(type){const texts={breakeven:['¿Qué es el punto de equilibrio?','Es el nivel de ventas necesario para cubrir costes y gastos. Por encima de ese nivel empiezas a generar resultado positivo. Si cambian tus precios, costes o gastos, también cambia el punto de equilibrio.'],decisions:['Decide con tus propios datos','El simulador modifica supuestos, no tus registros reales. Así puedes observar el posible impacto sobre resultado, caja, margen y punto de equilibrio antes de ejecutar una decisión.'],available:['¿Qué significa disponible?','Es lo que queda después de ingresos, gastos, ahorro planificado y pagos de deuda del período.'],focus:['¿Por qué esta recomendación?','El sistema detectó que los gastos variables aumentaron respecto al mes anterior mientras tu objetivo de ahorro se mantiene.'],cash:['Caja del negocio','Representa el dinero disponible. No es lo mismo que beneficio: una venta puede existir aunque todavía no haya sido cobrada.'],generic:['¿Cómo interpretar esta sección?','Cada indicador tiene una función financiera específica. Pulsa los iconos de información para aprender justo cuando lo necesitas.']};openModal(...(texts[type]||texts.generic))}
function showSim(type){const m=businessMonth(businessEngineData(),monthKey());const units=100;const base={units,unitPriceMinor:m.sales?Math.max(1,Math.round(m.sales/units)):1,unitVariableCostMinor:m.variableCosts?Math.max(0,Math.round(m.variableCosts/units)):0,fixedCostsMinor:m.operatingExpenses+m.debtInterest,openingCashMinor:0};const changes={hire:{fixedCostDeltaMinor:80000},price:{pricePctBp:1000},sales:{unitsPctBp:-1000}};const after=simulateBusiness(base,changes[type]);const title={hire:'Simulación: contratar por 800/mes',price:'Simulación: subir precios 10%',sales:'Simulación: ventas -10%'}[type];openModal(title,`Situación actual aproximada: <b>${moneyMinor(base.units*base.unitPriceMinor-base.units*base.unitVariableCostMinor-base.fixedCostsMinor,currency())}</b> de resultado.<br>Escenario simulado: <b>${moneyMinor(after.result,currency())}</b>.<br>Punto de equilibrio simulado: <b>${after.breakEven.units??'No alcanzable'} unidades de referencia</b>.<br><br>La simulación no modifica tus registros reales y muestra un escenario, no una predicción.`)}
function openModal(title,body){$('#modal').innerHTML=`<button class="ghost modalClose">×</button><h2>${title}</h2><p style="line-height:1.65;color:var(--muted)">${body}</p><button class="primary modalDone">Entendido</button>`;$('#modalWrap').classList.remove('hidden');$('.modalClose').onclick=$('.modalDone').onclick=()=>$('#modalWrap').classList.add('hidden')}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.setItem('feo-theme',state.theme);render()}
$$('.modeBtn').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;localStorage.setItem('feo-mode',state.mode);state.section='home';render()});$('#themeBtn').onclick=toggleTheme;$('#modalWrap').onclick=e=>{if(e.target.id==='modalWrap')e.currentTarget.classList.add('hidden')};
const tourSteps=[['Bienvenido a Finanzas en Orden','Aquí no vienes solo a registrar gastos. El sistema te ayuda a entender dónde estás y qué requiere tu atención.'],['Personal y Negocio','Son dos mundos separados. Puedes cambiar entre ellos sin mezclar datos ni indicadores.'],['Tu foco','El dashboard prioriza lo importante para que sepas qué mirar y qué acción considerar ahora.'],['Aprende en contexto','Cuando un concepto financiero no esté claro, pulsa ⓘ. La explicación aparece dentro de la herramienta.'],['Decisiones de negocio','En Negocio puedes simular una decisión antes de ejecutarla y medir después su impacto real.']];let tourIndex=0;
function startTour(force=false){if(!force&&localStorage.getItem('feo-tour')==='done')return;tourIndex=0;$('#tour').classList.remove('hidden');paintTour()}
function paintTour(){const [h,p]=tourSteps[tourIndex];$('#tourStep').innerHTML=`<span class="focusTag">${tourIndex+1} DE ${tourSteps.length}</span><h2>${h}</h2><p>${p}</p>`;$('#tourPrev').style.visibility=tourIndex?'visible':'hidden';$('#tourNext').textContent=tourIndex===tourSteps.length-1?'Terminar':'Siguiente'}
$('#tourNext').onclick=()=>{if(tourIndex===tourSteps.length-1){localStorage.setItem('feo-tour','done');$('#tour').classList.add('hidden')}else{tourIndex++;paintTour()}};$('#tourPrev').onclick=()=>{tourIndex=Math.max(0,tourIndex-1);paintTour()};$('#tourSkip').onclick=()=>{localStorage.setItem('feo-tour','done');$('#tour').classList.add('hidden')};



// V4 functional layer
const PROFILE_DEFAULT={name:'Usuario',email:'',country:'Ecuador',personalCurrency:'USD',businessCurrency:'USD',photo:''};
const sectionType={income:'income',expenses:'expense',debts:'debt',savings:'saving',goals:'goal',assets:'asset',sales:'sale',costs:'cost'};
const seed={personal:{income:[['Salario',3000],['Freelance',1200],['Ingresos extra',650]],expense:[['Vivienda',850],['Alimentación',620],['Transporte',240]],debt:[['Tarjeta principal',2200]],saving:[['Fondo emergencia',650]],goal:[['Viaje',3000]],asset:[['Cuenta ahorro',8400]]},business:{sale:[['Ventas online',7200],['Servicios',5300]],cost:[['Coste producto',4300]],expense:[['Alquiler',1200],['Marketing',900],['Software',250]]}};
let records={personal:{},business:{}};
let profileData={...PROFILE_DEFAULT};
let adminMode=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let syncTimer; const saveRecords=()=>{clearTimeout(syncTimer);syncTimer=setTimeout(()=>cloud.syncRecords(records,profileData).catch(showCloudError),120)};
function showCloudError(e){console.error(e);const c=$('#content');if(c)c.insertAdjacentHTML('afterbegin',`<div class="syncError">No se pudo guardar en la nube. Revisa tu conexión e inténtalo de nuevo.</div>`)}
const bucket=()=>records[state.mode]||(records[state.mode]={});
function listFor(type){return bucket()[type]||(bucket()[type]=[])}
function currency(){return state.mode==='personal'?profileData.personalCurrency:profileData.businessCurrency}
function recordView(){const type=sectionType[state.section]; const t=titles[state.section]; const list=listFor(type); const total=list.reduce((a,x)=>a+(Number.isSafeInteger(x.amountMinor)?x.amountMinor:Math.round(Number(x.amount||0)*100)),0); return `<div class="sectionHead"><div><h2>${t}</h2><p>${state.mode==='personal'?'Registra y revisa tus movimientos personales.':'Registra datos reales del negocio sin mezclarlos con simulaciones.'}</p></div><button class="primary" id="newRecord">＋ Nuevo registro</button></div><div class="kpis"><div class="kpi"><small>Total registrado</small><strong>${moneyMinor(total,currency())}</strong><em>${list.length} registros</em></div></div><div class="card" style="margin-top:20px"><h3>${t}</h3><div class="list">${list.length?list.map((x,i)=>`<div class="row"><div class="ico">${state.mode==='personal'?'○':'▣'}</div><div><b>${x.name}</b><small>${x.date||'28/09/2026'} · ${x.demo?'Demostración':'Real'}</small></div><div class="amount">${moneyMinor(Number.isSafeInteger(x.amountMinor)?x.amountMinor:Math.round(Number(x.amount||0)*100),currency())} <button class="ghost deleteRecord" data-i="${i}" style="padding:6px 9px;margin-left:8px">×</button></div></div>`).join(''):`<p class="sub" style="padding:18px 0">Todavía no hay registros. Añade el primero o carga datos de demostración desde Ajustes.</p>`}</div></div>`}
function generic(){if(state.section==='decisions')return decisions();if(state.section==='profile')return profile();if(state.section==='settings')return settings();if(state.section==='breakEven')return breakEven();if(state.section==='cashflow')return cashflowView();if(state.section==='results')return resultsView();if(state.section==='diagnostic')return diagnosticView();if(sectionType[state.section])return recordView(); const t=titles[state.section]||'Finanzas';return `<div class="sectionHead"><div><h2>${t}</h2><p>Análisis calculado a partir de tus registros.</p></div><button class="info" data-info="generic">i</button></div><div class="grid"><div class="card"><h3>${t} · Septiembre</h3><p class="sub">Esta vista no modifica registros.</p><div class="chart">${bars()}</div></div><div class="card focus"><span class="focusTag">INTERPRETACIÓN</span><h2>Entiende antes de actuar</h2><p class="sub">El diagnóstico usa los datos del período y mantiene Personal y Negocio separados.</p></div></div>`}
function cashflowView(){const b=records.business||{};const rows=[...(b.collection||[]).map((x,i)=>({...x,_type:'collection',_i:i,_label:'Cobro'})),...(b.cashPayment||[]).map((x,i)=>({...x,_type:'cashPayment',_i:i,_label:'Pago'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<div class="sectionHead"><div><h2>Flujo de caja</h2><p>Registra dinero realmente cobrado o pagado. No se confunde con ventas ni gastos devengados.</p></div><div style="display:flex;gap:8px"><button class="primary cashAdd" data-cash="collection">＋ Cobro</button><button class="ghost cashAdd" data-cash="cashPayment">− Pago</button></div></div><div class="card"><div class="list">${rows.length?rows.map(x=>`<div class="row"><div class="ico">${x._label==='Cobro'?'＋':'−'}</div><div><b>${x.name}</b><small>${x.date} · ${x._label} · ${x.demo?'Demostración':'Real'}</small></div><div class="amount">${x._label==='Cobro'?'+':'−'}${moneyMinor(asMinor(x),currency())} <button class="ghost deleteCash" data-type="${x._type}" data-i="${x._i}">×</button></div></div>`).join(''):'<p class="sub">Todavía no hay cobros ni pagos reales registrados.</p>'}</div></div>`}
function resultsView(){const m=businessMonth(businessEngineData(),monthKey());return `<div class="sectionHead"><div><h2>Resultado</h2><p>Resultado económico del mes; no equivale al efectivo disponible.</p></div></div><div class="kpis"><div class="kpi"><small>Ventas</small><strong>${moneyMinor(m.sales,currency())}</strong></div><div class="kpi"><small>Costos variables</small><strong>${moneyMinor(m.variableCosts,currency())}</strong></div><div class="kpi"><small>Gastos operativos</small><strong>${moneyMinor(m.operatingExpenses,currency())}</strong></div><div class="kpi"><small>Resultado</small><strong>${moneyMinor(m.operatingResult,currency())}</strong></div></div>`}
function diagnosticView(){const m=personalMonth(personalEngineData(),monthKey()),p=personalPosition(personalEngineData(),'2026-09-30');return `<div class="sectionHead"><div><h2>Diagnóstico financiero</h2><p>Lectura automática basada en tus registros del mes.</p></div></div><div class="grid"><div class="card"><h3>Liquidez mensual</h3><h2>${moneyMinor(m.available,currency())}</h2><p class="sub">${m.available>=0?'Disponible positivo después de compromisos registrados.':'Disponible negativo: las salidas registradas superan las entradas.'}</p></div><div class="card"><h3>Patrimonio</h3><h2>${moneyMinor(p.netWorth,currency())}</h2><p class="sub">Activos registrados menos saldos de deuda registrados.</p></div></div>`}
function openCashModal(type){const isIn=type==='collection';openModalForm(isIn?'Nuevo cobro':'Nuevo pago',`<div class="formGrid"><div class="field"><label>Concepto</label><input id="rName"></div><div class="field"><label>Monto (${currency()})</label><input id="rAmount" inputmode="decimal" placeholder="0.00"></div><div class="field"><label>Fecha</label><input id="rDate" type="date" value="2026-09-28"></div></div>`,()=>{const name=$('#rName').value.trim(),amountMinor=toMinor($('#rAmount').value);if(!name||amountMinor===null)return;const b=records.business||(records.business={});(b[type]||(b[type]=[])).push({name,amountMinor,currency:currency(),date:$('#rDate').value,demo:false});saveRecords();$('#modalWrap').classList.add('hidden');render()})}
function profile(){const initials=profileData.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();return `<div class="sectionHead"><div><h2>Mi perfil</h2><p>Identidad, país y monedas principales.</p></div><button class="primary" id="saveProfile">Guardar cambios</button></div><div class="grid"><div class="card"><div class="profileCard"><div class="profilePhoto" id="photoPreview" style="${profileData.photoUrl?`background-image:url(${profileData.photoUrl});background-size:cover;background-position:center;font-size:0`:''}">${initials}</div><div><h2 style="margin:0">${profileData.name}</h2><p class="sub">Cuenta principal</p><button class="ghost" id="changePhoto" style="margin-top:10px">Cambiar foto</button><input type="file" id="photoInput" accept="image/jpeg,image/png,image/webp" hidden></div></div></div><div class="card"><div class="formGrid"><div class="field"><label>Nombre</label><input id="pfName" value="${profileData.name}"></div><div class="field"><label>Correo</label><input id="pfEmail" value="${profileData.email}" disabled></div><div class="field"><label>País</label><select id="pfCountry">${['Ecuador','España','Estados Unidos','Colombia','México'].map(x=>`<option ${x===profileData.country?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Moneda personal</label><select id="pfPCurrency">${['USD','EUR','GBP','MXN','COP'].map(x=>`<option ${x===profileData.personalCurrency?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Moneda negocio</label><select id="pfBCurrency">${['USD','EUR','GBP','MXN','COP'].map(x=>`<option ${x===profileData.businessCurrency?'selected':''}>${x}</option>`).join('')}</select></div></div></div></div>`}
function demoActive(mode){return Object.values(records[mode]||{}).some(a=>(a||[]).some(x=>x.demo))}
function settings(){return `<div class="sectionHead"><div><h2>Ajustes</h2><p>Apariencia, seguridad y datos de demostración.</p></div></div><div class="grid"><div class="card"><h3>Apariencia</h3><div class="settingsRow"><div><b>Modo de color</b><small>Claro u oscuro.</small></div><button class="ghost" id="settingTheme">${state.theme==='dark'?'Oscuro':'Claro'}</button></div><div class="settingsRow"><div><b>Recorrido inicial</b><small>Vuelve a ver el tutorial cuando quieras.</small></div><button class="ghost" id="restartTour">Ver recorrido</button></div></div><div class="card"><h3>Seguridad de la cuenta</h3><div class="settingsRow"><div><b>Cambiar contraseña</b><small>Mínimo 8 caracteres.</small></div><button class="ghost" id="changePassword">Cambiar</button></div><div class="settingsRow"><div><b>Exportar mis datos</b><small>Descarga una copia JSON de tus datos de cuenta y finanzas.</small></div><button class="ghost" id="exportData">Exportar</button></div><div class="settingsRow"><div><b>Eliminar cuenta</b><small>Elimina permanentemente tu cuenta y datos asociados.</small></div><button class="ghost" id="deleteAccount">Eliminar</button></div></div><div class="card"><h3>Datos de demostración</h3>${['personal','business'].map(m=>`<div class="settingsRow"><div><b>${m==='personal'?'Personal':'Negocio'}</b><small>${m==='personal'?'12 meses':'24 meses'} de ejemplo; nunca elimina datos reales.</small></div><button class="ghost demoToggle" data-demo="${m}">${demoActive(m)?'Eliminar demo':'Cargar demo'}</button></div>`).join('')}</div></div>`}
function openRecordModal(){const type=sectionType[state.section];openModalForm(`Nuevo ${titles[state.section].toLowerCase()}`,`<div class="formGrid"><div class="field"><label>Nombre / concepto</label><input id="rName" placeholder="Ej. Salario"></div><div class="field"><label>Monto (${currency()})</label><input id="rAmount" type="number" min="0" step="0.01" placeholder="0.00"></div><div class="field"><label>Fecha</label><input id="rDate" type="date" value="2026-09-28"></div></div>`,()=>{const name=$('#rName').value.trim(),amountMinor=toMinor($('#rAmount').value);if(!name||amountMinor===null)return;listFor(type).push({name,amountMinor,currency:currency(),date:$('#rDate').value,demo:false});saveRecords();$('#modalWrap').classList.add('hidden');render()})}
function openModalForm(title,body,onSave){$('#modal').innerHTML=`<button class="ghost modalClose">×</button><h2>${title}</h2>${body}<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px"><button class="ghost modalCancel">Cancelar</button><button class="primary modalSave">Guardar</button></div>`;$('#modalWrap').classList.remove('hidden');$('.modalClose').onclick=$('.modalCancel').onclick=()=>$('#modalWrap').classList.add('hidden');$('.modalSave').onclick=onSave}
function toggleDemo(mode){records[mode] ||= {}; if(demoActive(mode)){Object.keys(records[mode]).forEach(k=>records[mode][k]=(records[mode][k]||[]).filter(x=>!x.demo))}else{Object.entries(seed[mode]).forEach(([k,arr])=>{records[mode][k] ||= [];arr.forEach(([name,amount],i)=>records[mode][k].push({name,amountMinor:Math.round(amount*100),currency:mode==='personal'?profileData.personalCurrency:profileData.businessCurrency,date:`2026-09-${String(10+i).padStart(2,'0')}`,demo:true}))})}saveRecords();render()}
function bindExtras(){$$('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info));$$('[data-sim]').forEach(b=>b.onclick=()=>showSim(b.dataset.sim));$('#restartTour')?.addEventListener('click',()=>startTour(true));$('#settingTheme')?.addEventListener('click',toggleTheme);$('#newRecord')?.addEventListener('click',openRecordModal);$$('.cashAdd').forEach(b=>b.onclick=()=>openCashModal(b.dataset.cash));$$('.deleteCash').forEach(b=>b.onclick=()=>{(records.business[b.dataset.type]||[]).splice(Number(b.dataset.i),1);saveRecords();render()});$$('.deleteRecord').forEach(b=>b.onclick=()=>{listFor(sectionType[state.section]).splice(Number(b.dataset.i),1);saveRecords();render()});$$('.demoToggle').forEach(b=>b.onclick=()=>toggleDemo(b.dataset.demo));$('#changePhoto')?.addEventListener('click',()=>$('#photoInput').click());$('#photoInput')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{profileData.photo=await cloud.uploadAvatar(f);profileData.photoUrl=await cloud.avatarObjectUrl(profileData.photo);await cloud.saveProfile(profileData);render()}catch(err){alert(err.message)}});$('#saveProfile')?.addEventListener('click',async()=>{profileData={...profileData,name:$('#pfName').value.trim()||profileData.name,country:$('#pfCountry').value,personalCurrency:$('#pfPCurrency').value,businessCurrency:$('#pfBCurrency').value};try{await cloud.saveProfile(profileData);render()}catch(e){showCloudError(e)}});$('#exportData')?.addEventListener('click',async()=>{try{const data=await cloud.exportMyData();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`finanzas-en-orden-datos-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){alert(e.message)}});$('#changePassword')?.addEventListener('click',()=>openModalForm('Cambiar contraseña','<div class="field"><label>Nueva contraseña</label><input id="newPassword" type="password" minlength="8" autocomplete="new-password"></div>',async()=>{try{await cloud.changePassword($('#newPassword').value);$('#modalWrap').classList.add('hidden');alert('Contraseña actualizada.')}catch(e){alert(e.message)}}));$('#deleteAccount')?.addEventListener('click',()=>openModalForm('Eliminar cuenta','<p>Esta acción es permanente. Escribe <b>ELIMINAR</b> para confirmar.</p><div class="field"><input id="deleteConfirm" autocomplete="off" placeholder="ELIMINAR"></div>',async()=>{if($('#deleteConfirm').value!=='ELIMINAR'){alert('Escribe ELIMINAR para confirmar.');return}try{await cloud.deleteMyAccount();location.reload()}catch(e){alert(e.message)}}))}
async function boot(){const recovery=cloud.acceptRecoveryFromUrl();if(recovery){showAuth('Enlace de recuperación validado. Abre Ajustes después de entrar para establecer tu nueva contraseña.')}const user=await cloud.currentUser();if(!user){showAuth();return}const qp=new URLSearchParams(location.search);if(qp.get('paypal')==='approved'&&qp.get('token')){try{await cloud.capturePayPalOrder(qp.get('token'));history.replaceState(null,'',location.pathname);await enterApp();return}catch(e){history.replaceState(null,'',location.pathname);showAccessPending(await cloud.myLicense().catch(()=>null),`PayPal regresó, pero todavía no pudimos confirmar el acceso: ${e.message}`);return}}await enterApp();if(recovery){state.section='settings';render();setTimeout(()=>$('#changePassword')?.click(),100)}}
async function enterApp(){try{const lic=await cloud.myLicense();adminMode=await cloud.isAdmin();if(!adminMode&&lic?.status!=='active'){showAccessPending(lic);return}const data=await cloud.loadData();records=data.records;profileData=data.profile;profileData.photoUrl=await cloud.avatarObjectUrl(profileData.photo);$('#authGate')?.classList.add('hidden');$('#accessGate')?.classList.add('hidden');$('#shell').classList.remove('hidden');$('#mobileNav').classList.remove('hidden');if(adminMode)injectAdminButton();render();setTimeout(()=>startTour(false),450)}catch(e){showAuth(e.message)}}
function showAccessPending(lic,message=''){ $('#authGate')?.classList.add('hidden');$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');const g=$('#accessGate');g?.classList.remove('hidden');const st=$('#accessStatus');if(st)st.textContent=message||(lic?`Estado de acceso: ${lic.status}.`:'Tu cuenta todavía no tiene una licencia activa.');const buy=$('#buyAccess');if(buy)buy.onclick=async()=>{buy.disabled=true;const old=buy.textContent;buy.textContent='Preparando PayPal…';try{const o=await cloud.createPayPalOrder();if(!o?.approve_url)throw new Error('PayPal no devolvió el enlace de aprobación.');location.assign(o.approve_url)}catch(e){st.textContent=e.message==='PAYPAL_NOT_CONFIGURED'?'PayPal todavía no está configurado para cobrar.':e.message;buy.disabled=false;buy.textContent=old}};const refresh=$('#refreshAccess');if(refresh)refresh.onclick=async()=>{refresh.disabled=true;try{const l=await cloud.myLicense();if(l?.status==='active'){await enterApp();return}st.textContent=l?`Estado de acceso: ${l.status}.`:'El pago todavía no ha sido confirmado.'}catch(e){st.textContent=e.message}finally{refresh.disabled=false}}}
function injectAdminButton(){const b=document.createElement('button');b.id='adminOpen';b.innerHTML='▦ <span>Admin</span>';b.onclick=()=>openAdmin();document.querySelector('.sideBottom')?.prepend(b)}
async function openAdmin(){
 try{
  const d=await cloud.adminDashboard();
  const rows=(d.users||[]).map(u=>{
   const l=u.license, pay=u.last_payment;
   const payText=pay?`${esc(pay.status)} · ${esc(pay.currency)} ${(Number(pay.amount_minor)/100).toFixed(2)}`:'Sin pago registrado';
   const action=l?`<button class="ghost adminLicense" data-user="${u.id}" data-status="${l.status==='active'?'revoked':'active'}">${l.status==='active'?'Desactivar':'Activar'}</button>`:'—';
   return `<div class="adminRow"><div><b>${esc(u.full_name||u.email||'Usuario')}</b><small>${esc(u.country||'—')} · ${esc(u.email||'Sin correo')}</small></div><div><b>${esc(l?.status||'sin licencia')}</b><small>${payText}</small></div><div>${action}</div><div><button class="ghost adminNote" data-user="${u.id}">Nota</button></div></div>`;
  }).join('');
  $('#content').innerHTML=`<div class="sectionHead"><div><h2>Administración</h2><p>Acceso, pagos y soporte. Los movimientos financieros no están disponibles aquí.</p></div></div><div class="card"><div class="adminTable">${rows||'<p class="sub">Aún no hay usuarios.</p>'}</div></div>`;
  $$('.adminLicense').forEach(b=>b.onclick=async()=>{try{await cloud.adminSetLicense(b.dataset.user,b.dataset.status);await openAdmin()}catch(e){alert(e.message)}});
  $$('.adminNote').forEach(b=>b.onclick=()=>openModalForm('Nota de soporte','<div class="field"><label>Nota interna</label><textarea id="supportNote" maxlength="1000"></textarea></div>',async()=>{await cloud.adminAddNote(b.dataset.user,$('#supportNote').value);$('#modalWrap').classList.add('hidden')}));
 }catch(e){alert(e.message)}
}

function showAuth(message=''){const gate=$('#authGate');gate?.classList.remove('hidden');$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');if(message&&$('#authMsg'))$('#authMsg').textContent=message}
window.feoAuth={async forgot(){const email=$('#authEmail').value.trim(),msg=$('#authMsg');try{await cloud.requestPasswordReset(email);msg.textContent='Si existe una cuenta con ese correo, recibirás instrucciones para restablecer la contraseña.'}catch(e){msg.textContent=e.message}},async submit(mode){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,msg=$('#authMsg');msg.textContent='';try{if(mode==='signup'){const s=await cloud.signUp(email,password);if(!s?.access_token){msg.textContent='Cuenta creada. Revisa tu correo para confirmar el acceso.';return}}else await cloud.signIn(email,password);await enterApp()}catch(e){msg.textContent=e.message}},logout(){cloud.signOut();location.reload()}};
boot();
