import { personalMonth, personalPosition, businessMonth, breakEven as calcBreakEven, simulateBusiness } from './financial-engine.js';
import * as cloud from './supabase-store.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={mode:localStorage.getItem('feo-mode')||'personal',section:'home',theme:localStorage.getItem('feo-theme')||'system',sound:localStorage.getItem('feo-sound')!=='off',onboardingChoice:'personal',onboardingMode:'personal',onboardingStep:0};
const money=(n,c='USD')=>new Intl.NumberFormat('es-ES',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const moneyMinor=(n,c='USD')=>new Intl.NumberFormat('es-ES',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format((n||0)/100);
const toMinor=s=>{const v=String(s??'').trim().replace(',','.');if(!/^(?:0|[1-9]\d*)(?:\.\d{1,2})?$/.test(v))return null;const [a,b='']=v.split('.');const n=Number(a)*100+Number((b+'00').slice(0,2));return Number.isSafeInteger(n)?n:null};
const navs={personal:[['home','⌂','Inicio'],['movements','◉','Movimientos'],['plan','□','Plan'],['decisions','◇','Decisiones'],['more','•••','Más']],business:[['home','⌂','Inicio'],['movements','◉','Movimientos'],['plan','□','Plan'],['decisions','◇','Decisiones'],['more','•••','Más']]};
const personal={income:4850,expenses:3120,savings:650,debt:350,assets:18400,totalDebt:6200};
const business={sales:12500,collections:10800,costs:4300,expenses:3100,debtPayments:650,cash:6420};
const systemTheme=()=>window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light';
function applyTheme(){const resolved=state.theme==='system'?systemTheme():state.theme;document.documentElement.dataset.theme=resolved;document.documentElement.dataset.themePreference=state.theme;const meta=document.querySelector('meta[name=theme-color]');if(meta)meta.content=resolved==='dark'?'#071f1d':'#f3f6f4'}
applyTheme();
window.matchMedia?.('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(state.theme==='system')applyTheme()});
function renderNav(){const items=navs[state.mode];$('#nav').innerHTML=items.map(([id,ic,t])=>`<button data-section="${id}" class="${state.section===id?'active':''}"><b>${ic}</b><span>${t}</span></button>`).join('');$('#mobileNav').innerHTML=items.map(([id,ic,t])=>`<button data-section="${id}" class="${state.section===id?'active':''}"><i>${ic}</i>${t}</button>`).join('');bindNav()}
function bindNav(){$$('[data-section]').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;render()})}
function bars(){return [48,64,55,78,69,88,74].map((h,i)=>`<div class="bar ${i===5?'active':''}" style="height:${h}%"><span>${['Mar','Abr','May','Jun','Jul','Ago','Sep'][i]}</span></div>`).join('')}
function monthKey(){return '2026-09'}
function asMinor(x){return Number.isSafeInteger(x?.amountMinor)?x.amountMinor:0}
function personalEngineData(){const b=records.personal||{};return {income:(b.income||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),expense:(b.expense||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),saving:(b.saving||[]).map(x=>({date:x.date,amountMinor:asMinor(x),direction:x.direction||'deposit'})),debtPayments:(b.debtPayment||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),assets:(b.asset||[]).map((x,i)=>({id:x.id||`asset-${i}`,date:x.date,valueMinor:asMinor(x)})),debts:(b.debt||[]).map((x,i)=>({id:x.id||`debt-${i}`,date:x.date,balanceMinor:asMinor(x)}))}}
function businessEngineData(){const b=records.business||{};return {sales:(b.sale||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),collections:(b.collection||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),variableCosts:(b.cost||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),operatingExpenses:(b.expense||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),cashPayments:(b.cashPayment||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),debtPrincipalPayments:(b.debtPrincipal||[]).map(x=>({date:x.date,amountMinor:asMinor(x)})),debtInterestPayments:(b.debtInterest||[]).map(x=>({date:x.date,amountMinor:asMinor(x)}))}}
function personalScore(m,pos){let score=50;if(m.available>0)score+=12;if((m.savingsRateBp||0)>=1000)score+=10;if((m.savingsRateBp||0)>=2000)score+=6;if(pos.netWorth>0)score+=8;if(pos.debts>0&&pos.assets>pos.debts)score+=5;if(m.expense>m.income)score-=18;return Math.max(0,Math.min(100,score))}
function businessScore(m){let score=48;if(m.operatingResult>0)score+=15;if(m.cashFlow>0)score+=12;if(m.collections>=m.sales*.7)score+=8;if(m.sales>m.variableCosts+m.operatingExpenses)score+=7;if(m.cashFlow<0)score-=16;return Math.max(0,Math.min(100,score))}
function microBars(values=[32,45,38,58,50,70,78]){const max=Math.max(...values,1);return `<div class="microBars">${values.map((v,i)=>`<i class="${i===values.length-1?'active':''}" style="height:${Math.max(14,Math.round(v/max*100))}%"></i>`).join('')}</div>`}
function nowNextGoal(items){return `<div class="triad">${items.map(([k,label,value,sub,icon])=>`<div class="triadCard"><span class="triadIcon">${icon}</span><div><small>${k}</small><b>${label}</b><strong>${value}</strong>${sub?`<em>${sub}</em>`:''}</div></div>`).join('')}</div>`}
function home(){if(state.mode==='personal'){const m=personalMonth(personalEngineData(),monthKey()),pos=personalPosition(personalEngineData(),'2026-09-30'),score=personalScore(m,pos);const expPct=m.income?Math.round(m.expense*100/m.income):0;return `<div class="dashboardLead"><div class="scoreCard"><span class="eyebrow">TU SITUACIÓN FINANCIERA</span><div class="scoreLine"><strong>${score}</strong><span>/ 100</span></div><p>${score>=75?'Vas en buena dirección.':score>=55?'Hay una base estable, con espacio para mejorar.':'Hay varios puntos que requieren atención.'}</p><div class="scoreProgress"><i style="width:${score}%"></i></div><button class="scoreArrow" data-section="decisions">→</button></div><div class="priorityCard"><span class="eyebrow">LO MÁS IMPORTANTE AHORA</span><div class="priorityBody"><div class="priorityIcon">↗</div><div><h3>${expPct>65?'Tus gastos están tomando demasiado espacio':'Protege tu disponible antes de comprometerlo'}</h3><p>${expPct>65?`Los gastos equivalen al ${expPct}% de tus ingresos este mes.`:`Hoy tienes ${moneyMinor(m.available,currency())} disponibles después de tus movimientos registrados.`}</p><button class="primary" data-section="decisions">Ver recomendación →</button></div></div></div></div>${nowNextGoal([['AHORA','Disponible',moneyMinor(m.available,currency()),'', '▣'],['PRÓXIMO','Revisar pagos','Esta semana','Evita sorpresas de caja','□'],['META','Tasa de ahorro',m.savingsRateBp==null?'—':(m.savingsRateBp/100).toFixed(1)+'%','Objetivo recomendado: 20%','◎']])}<div class="dashboardGrid"><div class="card chartCard"><div class="cardHead"><div><span class="eyebrow">EVOLUCIÓN</span><h3>Tu situación financiera</h3></div><button class="info" data-info="available">i</button></div>${microBars([44,51,48,60,64,68,score])}<div class="chartLegend"><span>Mar</span><span>Abr</span><span>May</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Sep</span></div></div><div class="card compactList"><span class="eyebrow">ESTE MES</span><div class="metricRow"><span>Ingresos</span><b>${moneyMinor(m.income,currency())}</b></div><div class="metricRow"><span>Gastos</span><b>${moneyMinor(m.expense,currency())}</b></div><div class="metricRow"><span>Ahorro neto</span><b>${moneyMinor(m.netSavings,currency())}</b></div><div class="metricRow"><span>Patrimonio</span><b>${moneyMinor(pos.netWorth,currency())}</b></div></div></div>`}return businessHome()}
function businessHome(){const m=businessMonth(businessEngineData(),monthKey()),score=businessScore(m);const margin=m.sales?Math.round(m.operatingResult*1000/m.sales)/10:null;return `<div class="dashboardLead"><div class="scoreCard"><span class="eyebrow">SALUD DE TU NEGOCIO</span><div class="scoreLine"><strong>${score}</strong><span>/ 100</span></div><p>${score>=75?'Buen potencial de crecimiento.':score>=55?'La operación es funcional, pero hay margen de mejora.':'La caja o el resultado requieren atención.'}</p><div class="scoreProgress"><i style="width:${score}%"></i></div><button class="scoreArrow" data-section="decisions">→</button></div><div class="priorityCard"><span class="eyebrow">LO MÁS IMPORTANTE AHORA</span><div class="priorityBody"><div class="priorityIcon">↗</div><div><h3>${margin!=null&&margin<20?'Tu margen necesita protección':'Resultado y caja deben avanzar juntos'}</h3><p>${margin!=null?`Tu margen operativo aproximado es ${margin}%.`:'Registra ventas y cobros para separar rentabilidad de efectivo.'}</p><button class="primary" data-section="decisions">Ver recomendación →</button></div></div></div></div>${nowNextGoal([['AHORA','Caja del mes',moneyMinor(m.cashFlow,currency()),'Cobros reales − pagos reales','▣'],['PRÓXIMO','Revisar cobros',moneyMinor(m.collections,currency()),'No confundas venta con efectivo','□'],['META','Resultado',moneyMinor(m.operatingResult,currency()),margin==null?'Sin ventas':`${margin}% sobre ventas`,'◎']])}<div class="dashboardGrid"><div class="card chartCard"><div class="cardHead"><div><span class="eyebrow">NEGOCIO</span><h3>Ventas vs. caja</h3></div><button class="info" data-info="cash">i</button></div>${microBars([42,57,52,69,63,81,score])}<div class="chartLegend"><span>Mar</span><span>Abr</span><span>May</span><span>Jun</span><span>Jul</span><span>Ago</span><span>Sep</span></div></div><div class="card compactList"><span class="eyebrow">ESTE MES</span><div class="metricRow"><span>Ventas</span><b>${moneyMinor(m.sales,currency())}</b></div><div class="metricRow"><span>Cobros</span><b>${moneyMinor(m.collections,currency())}</b></div><div class="metricRow"><span>Resultado</span><b>${moneyMinor(m.operatingResult,currency())}</b></div><div class="metricRow"><span>Flujo de caja</span><b>${moneyMinor(m.cashFlow,currency())}</b></div></div></div>`}
const titles={movements:'Movimientos',plan:'Plan',decisions:'Decisiones',more:'Más',income:'Ingresos',expenses:'Gastos',debts:'Deudas',savings:'Ahorros',goals:'Metas',assets:'Activos',diagnostic:'Diagnóstico financiero',sales:'Ventas',costs:'Costos',cashflow:'Flujo de caja',breakEven:'Punto de equilibrio',results:'Resultado',profile:'Mi perfil',settings:'Ajustes'};
function quickAction(id,icon,title,copy){return `<button class="moduleCard" data-section="${id}"><span>${icon}</span><b>${title}</b><small>${copy}</small><i>→</i></button>`}
function movementsView(){if(state.mode==='personal')return `<div class="sectionHead"><div><h2>Movimientos</h2><p>Registra lo que entra y lo que sale. Lo demás se calcula detrás.</p></div></div><div class="moduleGrid">${quickAction('income','＋','Ingresos','Sueldo, ventas personales y otros ingresos')}${quickAction('expenses','−','Gastos','Fijos, variables y gastos del día a día')}${quickAction('savings','◇','Ahorro','Aportes o retiros de tus ahorros')}${quickAction('debts','□','Deudas','Saldos y pagos de tus obligaciones')}</div>`;return `<div class="sectionHead"><div><h2>Movimientos</h2><p>Separa lo económico de lo que realmente entra y sale de caja.</p></div></div><div class="moduleGrid">${quickAction('sales','＋','Ventas','Lo vendido, aunque todavía no se haya cobrado')}${quickAction('costs','−','Costos','Costos directamente ligados a vender')}${quickAction('expenses','▤','Gastos','Gastos operativos del negocio')}${quickAction('cashflow','↕','Cobros y pagos','Dinero que realmente entró o salió')}</div>`}
function planView(){if(state.mode==='personal')return `<div class="sectionHead"><div><h2>Plan</h2><p>Convierte tu situación actual en objetivos concretos.</p></div></div><div class="moduleGrid">${quickAction('goals','◎','Metas','Ahorro, compras y objetivos financieros')}${quickAction('debts','□','Deudas','Controla saldos y prioridad de pago')}${quickAction('assets','▣','Patrimonio','Activos y posición patrimonial')}${quickAction('diagnostic','✦','Diagnóstico','Entiende qué está frenando tu avance')}</div>`;return `<div class="sectionHead"><div><h2>Plan</h2><p>Define el nivel de ventas y estructura que necesita tu negocio.</p></div></div><div class="moduleGrid">${quickAction('breakEven','◎','Punto de equilibrio','Cuánto necesitas vender para cubrir tu estructura')}${quickAction('results','▣','Resultado','Ventas menos costos y gastos')}${quickAction('cashflow','↕','Caja','Lo cobrado y pagado realmente')}${quickAction('decisions','✦','Escenarios','Prueba decisiones antes de ejecutarlas')}</div>`}
function moreView(){return `<div class="sectionHead"><div><h2>Más</h2><p>Herramientas secundarias, cuenta y configuración.</p></div></div><div class="moduleGrid">${state.mode==='personal'?quickAction('diagnostic','✦','Diagnóstico','Lectura automática de tu situación'):quickAction('results','▣','Resultados','Rentabilidad separada de la caja')}${quickAction('profile','○','Perfil','País, monedas y datos de tu cuenta')}${quickAction('settings','⚙','Ajustes','Apariencia, datos demo y seguridad')}</div>`}
function personalDecisions(){const m=personalMonth(personalEngineData(),monthKey());const pos=personalPosition(personalEngineData(),'2026-09-30');const expenseCut=Math.max(0,Math.round(m.expense*.12));return `<div class="sectionHead"><div><h2>Decisiones</h2><p>Una pregunta a la vez. Te mostramos el efecto antes de actuar.</p></div></div><div class="decisionHero"><span class="eyebrow">¿QUÉ ESTÁS PENSANDO HACER?</span><div class="moduleGrid decisionOptions"><button class="moduleCard personalDecision" data-personal-decision="expenses"><span>↘</span><b>Reducir gastos</b><small>Encuentra cuánto podrías liberar sin tocar lo esencial.</small><i>→</i></button><button class="moduleCard personalDecision" data-personal-decision="save"><span>◇</span><b>Ahorrar más</b><small>Calcula un objetivo mensual realista.</small><i>→</i></button><button class="moduleCard personalDecision" data-personal-decision="debt"><span>□</span><b>Salir de deudas</b><small>Ordena el siguiente pago por prioridad.</small><i>→</i></button><button class="moduleCard personalDecision" data-personal-decision="invest"><span>◎</span><b>Invertir</b><small>Primero verifica liquidez y carga de deuda.</small><i>→</i></button></div></div><div class="card decisionSummary"><span class="eyebrow">RECOMENDACIÓN ACTUAL</span><h2>${expenseCut?`Reducir 12% de tus gastos liberaría ${moneyMinor(expenseCut,currency())}`:'Registra gastos para calcular una recomendación concreta'}</h2><p>Esto es una simulación orientativa basada en tus registros actuales; no cambia tus datos.</p></div>`}
function decisions(){if(state.mode==='personal')return personalDecisions();const m=businessMonth(businessEngineData(),monthKey());return `<div class="sectionHead"><div><h2>Decisiones</h2><p>Prueba una decisión antes de llevarla a tu negocio real.</p></div><button class="info" data-info="decisions">i</button></div><div class="decisionHero"><span class="eyebrow">¿QUÉ ESTÁS PENSANDO HACER?</span><div class="moduleGrid decisionOptions"><div class="moduleCard decision" data-sim="price"><span>↗</span><b>Subir precios</b><small>Evalúa margen, resultado y equilibrio.</small><i>→</i></div><div class="moduleCard decision" data-sim="hire"><span>＋</span><b>Contratar</b><small>Mide el impacto de un nuevo costo fijo.</small><i>→</i></div><div class="moduleCard decision" data-sim="sales"><span>◎</span><b>Cambio en ventas</b><small>Simula un escenario de ventas -10%.</small><i>→</i></div></div></div><div class="card decisionSummary"><span class="eyebrow">SITUACIÓN ACTUAL</span><div class="metricRow"><span>Ventas</span><b>${moneyMinor(m.sales,currency())}</b></div><div class="metricRow"><span>Resultado</span><b>${moneyMinor(m.operatingResult,currency())}</b></div><div class="metricRow"><span>Flujo de caja</span><b>${moneyMinor(m.cashFlow,currency())}</b></div><p>Los escenarios no son predicciones y nunca modifican tus registros.</p></div>`}
function breakEven(){return `<div class="sectionHead"><div><h2>Punto de equilibrio</h2><p>Cuánto necesitas vender para cubrir tus costes y gastos.</p></div><button class="info" data-info="breakeven">i</button></div><div class="hero"><small>Punto de equilibrio mensual</small><h2>${money(8260)}</h2><div class="delta">Tus ventas actuales están ${money(4240)} por encima</div></div><div class="grid"><div class="card"><h3>Lectura rápida</h3><p class="sub">Por encima de ${money(8260)} empiezas a generar resultado positivo bajo la estructura actual.</p></div><div class="card focus"><span class="focusTag">¿QUÉ PASA SI...?</span><h2>Prueba una decisión</h2><p class="sub">Una contratación, un aumento de alquiler o un cambio de precio mueve tu punto de equilibrio.</p><button class="primary" data-section="decisions" style="margin-top:16px">Abrir simulador</button></div></div>`}
function profileLegacy(){return `<div class="sectionHead"><div><h2>Mi perfil</h2><p>Tu identidad y preferencias financieras.</p></div></div><div class="grid"><div class="card"><div class="profileCard"><div class="profilePhoto">AZ</div><div><h2 style="margin:0">Alejandro Zambrano</h2><p class="sub">Cuenta principal</p><button class="ghost" style="margin-top:10px">Cambiar foto</button></div></div></div><div class="card"><div class="formGrid"><div class="field"><label>Nombre</label><input value="Alejandro Zambrano"></div><div class="field"><label>Correo</label><input value="usuario@ejemplo.com"></div><div class="field"><label>País</label><select><option>Ecuador</option><option>España</option></select></div><div class="field"><label>Moneda personal</label><select><option>USD — Dólar</option><option>EUR — Euro</option></select></div></div></div></div>`}
function settingsLegacy(){return `<div class="sectionHead"><div><h2>Ajustes</h2><p>Personaliza la experiencia y controla los datos de prueba.</p></div></div><div class="grid"><div class="card"><h3>Apariencia</h3><div class="settingsRow"><div><b>Modo de color</b><small>Claro, oscuro o según tu dispositivo.</small></div><button class="ghost" id="settingTheme">${state.theme==='dark'?'Oscuro':'Claro'}</button></div><div class="settingsRow"><div><b>Recorrido inicial</b><small>Puedes volver a ver el tutorial cuando quieras.</small></div><button class="ghost" id="restartTour">Ver recorrido</button></div></div><div class="card"><h3>Datos de demostración</h3><div class="settingsRow"><div><b>Personal</b><small>12 meses de datos de ejemplo certificados.</small></div><button class="ghost">Cargar / eliminar</button></div><div class="settingsRow"><div><b>Negocio</b><small>24 meses para explorar resultados y decisiones.</small></div><button class="ghost">Cargar / eliminar</button></div><p class="sub" style="margin-top:14px">Los datos demo se identifican por separado y nunca deben borrar datos reales.</p></div></div>`}
function render(){renderNav();$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));const name=(profileData.name||'').split(' ')[0]||'Usuario';$('#pageTitle').textContent=state.section==='home'?(state.mode==='personal'?`Hola, ${name}`:'Mi negocio'):titles[state.section]||'Finanzas en Orden';$('#content').innerHTML=state.section==='home'?home():generic();bindNav();bindExtras()}
function bindExtrasLegacy(){$$('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info));$$('[data-sim]').forEach(b=>b.onclick=()=>showSim(b.dataset.sim));$$('[data-personal-decision]').forEach(b=>b.onclick=()=>showPersonalDecision(b.dataset.personalDecision));$('#restartTour')?.addEventListener('click',()=>startTour(true));$('#settingTheme')?.addEventListener('click',toggleTheme)}
function showInfo(type){const texts={breakeven:['¿Qué es el punto de equilibrio?','Es el nivel de ventas necesario para cubrir costes y gastos. Por encima de ese nivel empiezas a generar resultado positivo. Si cambian tus precios, costes o gastos, también cambia el punto de equilibrio.'],decisions:['Decide con tus propios datos','El simulador modifica supuestos, no tus registros reales. Así puedes observar el posible impacto sobre resultado, caja, margen y punto de equilibrio antes de ejecutar una decisión.'],available:['¿Qué significa disponible?','Es lo que queda después de ingresos, gastos, ahorro planificado y pagos de deuda del período.'],focus:['¿Por qué esta recomendación?','El sistema detectó que los gastos variables aumentaron respecto al mes anterior mientras tu objetivo de ahorro se mantiene.'],cash:['Caja del negocio','Representa el dinero disponible. No es lo mismo que beneficio: una venta puede existir aunque todavía no haya sido cobrada.'],generic:['¿Cómo interpretar esta sección?','Cada indicador tiene una función financiera específica. Pulsa los iconos de información para aprender justo cuando lo necesitas.']};openModal(...(texts[type]||texts.generic))}
function showPersonalDecision(type){const m=personalMonth(personalEngineData(),monthKey()),p=personalPosition(personalEngineData(),'2026-09-30');const expenseCut=Math.round(m.expense*.12);const savingsTarget=Math.round(m.income*.2);const texts={expenses:['Reducir mis gastos',m.expense?`Si reduces 12% de tus gastos actuales, liberarías aproximadamente <b>${moneyMinor(expenseCut,currency())}</b> este mes.`:'Registra tus gastos para estimar cuánto podrías liberar.'],save:['Ahorrar más',m.income?`Un objetivo del 20% de tus ingresos sería <b>${moneyMinor(savingsTarget,currency())}</b> al mes. Compáralo con tu ahorro actual antes de comprometerte.`:'Registra ingresos para calcular un objetivo de ahorro.'],debt:['Salir de deudas',p.debts?`Tienes <b>${moneyMinor(p.debts,currency())}</b> de deuda registrada. Prioriza pagos sin dejar tu disponible mensual en negativo.`:'No hay deuda registrada actualmente.'],invest:['Invertir',m.available>0&&p.debts<=p.assets*.35?`Tu disponible es <b>${moneyMinor(m.available,currency())}</b>. Antes de invertir, confirma fondo de emergencia y próximos pagos.`:'Antes de invertir, fortalece liquidez y revisa deuda registrada.']};openModal(texts[type][0],texts[type][1]+'<br><br>Esta orientación usa tus registros actuales y no constituye una predicción.')}
function showSim(type){const m=businessMonth(businessEngineData(),monthKey());const units=100;const base={units,unitPriceMinor:m.sales?Math.max(1,Math.round(m.sales/units)):1,unitVariableCostMinor:m.variableCosts?Math.max(0,Math.round(m.variableCosts/units)):0,fixedCostsMinor:m.operatingExpenses+m.debtInterest,openingCashMinor:0};const changes={hire:{fixedCostDeltaMinor:80000},price:{pricePctBp:1000},sales:{unitsPctBp:-1000}};const after=simulateBusiness(base,changes[type]);const title={hire:'Simulación: contratar por 800/mes',price:'Simulación: subir precios 10%',sales:'Simulación: ventas -10%'}[type];openModal(title,`Situación actual aproximada: <b>${moneyMinor(base.units*base.unitPriceMinor-base.units*base.unitVariableCostMinor-base.fixedCostsMinor,currency())}</b> de resultado.<br>Escenario simulado: <b>${moneyMinor(after.result,currency())}</b>.<br>Punto de equilibrio simulado: <b>${after.breakEven.units??'No alcanzable'} unidades de referencia</b>.<br><br>La simulación no modifica tus registros reales y muestra un escenario, no una predicción.`)}
function openModal(title,body){$('#modal').innerHTML=`<button class="ghost modalClose">×</button><h2>${title}</h2><p style="line-height:1.65;color:var(--muted)">${body}</p><button class="primary modalDone">Entendido</button>`;$('#modalWrap').classList.remove('hidden');$('.modalClose').onclick=$('.modalDone').onclick=()=>$('#modalWrap').classList.add('hidden')}
const themeLabels={light:'Claro',dark:'Oscuro',system:'Sistema'};
function cycleTheme(){const order=['light','dark','system'];state.theme=order[(order.indexOf(state.theme)+1)%order.length];profileData.theme=state.theme;localStorage.setItem('feo-theme',state.theme);applyTheme();cloud.saveProfile(profileData).catch(()=>{});render()}
function setSound(enabled){state.sound=!!enabled;localStorage.setItem('feo-sound',state.sound?'on':'off')}
function playModeSwitchSound(nextMode){if(!state.sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime;osc.type='sine';const start=nextMode==='business'?430:540,end=nextMode==='business'?560:430;osc.frequency.setValueAtTime(start,now);osc.frequency.exponentialRampToValueAtTime(end,now+.11);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.045,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.14);osc.connect(gain);gain.connect(ctx.destination);osc.start(now);osc.stop(now+.15);osc.onended=()=>ctx.close().catch(()=>{})}catch{}}
$$('.modeBtn').forEach(b=>b.onclick=()=>{const next=b.dataset.mode;if(next!==state.mode)playModeSwitchSound(next);state.mode=next;localStorage.setItem('feo-mode',state.mode);state.section='home';render()});$('#themeBtn').onclick=cycleTheme;$('#modalWrap').onclick=e=>{if(e.target.id==='modalWrap')e.currentTarget.classList.add('hidden')};
const tourByMode={personal:[['Tu punto de partida','Aquí ves tu situación financiera y la acción más importante ahora.'],['Registra tus movimientos','En Movimientos agrega ingresos, gastos, ahorro y deuda.'],['Recibe recomendaciones','Decisiones te muestra qué podrías hacer según tus propios registros.'],['Define y sigue tu plan','En Plan reúnes metas, deudas, patrimonio y diagnóstico.']],business:[['Vista principal de tu negocio','Aquí ves salud del negocio, resultado, caja y la recomendación principal.'],['Registra ventas y caja','En Movimientos mantén separadas ventas, costos, cobros y pagos.'],['Conoce tu punto de equilibrio','En Plan sabrás cuánto necesitas vender para cubrir tu estructura.'],['Prueba antes de decidir','Decisiones simula escenarios sin modificar los datos reales.']]};let tourIndex=0;
function startTour(force=false){if(!force&&profileData.tutorialCompleted)return;tourIndex=0;$('#tour').classList.remove('hidden');paintTour()}
function paintTour(){const steps=tourByMode[state.mode], [h,p]=steps[tourIndex];$('#tourStep').innerHTML=`<span class="focusTag">${tourIndex+1} / ${steps.length}</span><h2>${h}</h2><p>${p}</p>`;$('#tourPrev').style.visibility=tourIndex?'visible':'hidden';$('#tourNext').textContent=tourIndex===steps.length-1?'Entendido':'Siguiente'}
async function finishTour(){profileData.tutorialCompleted=true;$('#tour').classList.add('hidden');try{await cloud.saveProfile(profileData)}catch(e){showCloudError(e)}}
$('#tourNext').onclick=()=>{const steps=tourByMode[state.mode];if(tourIndex===steps.length-1)finishTour();else{tourIndex++;paintTour()}};$('#tourPrev').onclick=()=>{tourIndex=Math.max(0,tourIndex-1);paintTour()};$('#tourSkip').onclick=finishTour;

// V4 functional layer
const PROFILE_DEFAULT={name:'Usuario',email:'',country:'Ecuador',personalCurrency:'USD',businessCurrency:'USD',photo:'',tutorialCompleted:false,theme:'system'};
const sectionType={income:'income',expenses:'expense',debts:'debt',savings:'saving',goals:'goal',assets:'asset',sales:'sale',costs:'cost'};
const seed={personal:{income:[['Salario',3000],['Freelance',1200],['Ingresos extra',650]],expense:[['Vivienda',850],['Alimentación',620],['Transporte',240]],debt:[['Tarjeta principal',2200]],saving:[['Fondo emergencia',650]],goal:[['Viaje',3000]],asset:[['Cuenta ahorro',8400]]},business:{sale:[['Ventas online',7200],['Servicios',5300]],cost:[['Coste producto',4300]],expense:[['Alquiler',1200],['Marketing',900],['Software',250]]}};
let records={personal:{},business:{}};
let profileData={...PROFILE_DEFAULT};
let adminMode=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let syncTimer; const saveRecords=()=>{clearTimeout(syncTimer);syncTimer=setTimeout(()=>cloud.syncRecords(records,profileData).catch(showCloudError),120)};
function showCloudError(e){console.error(e);const c=$('#content');if(c)c.insertAdjacentHTML('afterbegin',`<div class="syncError">No se pudo guardar en la nube. Revisa tu conexión e inténtalo de nuevo.</div>`)}
const bucket=()=>records[state.mode]||(records[state.mode]={});
function listFor(type){return bucket()[type]||(bucket()[type]=[])}
function currency(){return state.mode==='personal'?profileData.personalCurrency:profileData.businessCurrency}
function recordView(){const type=sectionType[state.section]; const t=titles[state.section]; const list=listFor(type); const total=list.reduce((a,x)=>a+(Number.isSafeInteger(x.amountMinor)?x.amountMinor:Math.round(Number(x.amount||0)*100)),0); return `<div class="sectionHead"><div><h2>${t}</h2><p>${state.mode==='personal'?'Registra y revisa tus movimientos personales.':'Registra datos reales del negocio sin mezclarlos con simulaciones.'}</p></div><button class="primary" id="newRecord">＋ Nuevo registro</button></div><div class="kpis"><div class="kpi"><small>Total registrado</small><strong>${moneyMinor(total,currency())}</strong><em>${list.length} registros</em></div></div><div class="card" style="margin-top:20px"><h3>${t}</h3><div class="list">${list.length?list.map((x,i)=>`<div class="row"><div class="ico">${state.mode==='personal'?'○':'▣'}</div><div><b>${x.name}</b><small>${x.date||'28/09/2026'} · ${x.demo?'Demostración':'Real'}</small></div><div class="amount">${moneyMinor(Number.isSafeInteger(x.amountMinor)?x.amountMinor:Math.round(Number(x.amount||0)*100),currency())} <button class="ghost deleteRecord" data-i="${i}" style="padding:6px 9px;margin-left:8px">×</button></div></div>`).join(''):`<p class="sub" style="padding:18px 0">Todavía no hay registros. Añade el primero o carga datos de demostración desde Ajustes.</p>`}</div></div>`}
function generic(){if(state.section==='movements')return movementsView();if(state.section==='plan')return planView();if(state.section==='decisions')return decisions();if(state.section==='more')return moreView();if(state.section==='profile')return profile();if(state.section==='settings')return settings();if(state.section==='breakEven')return breakEven();if(state.section==='cashflow')return cashflowView();if(state.section==='results')return resultsView();if(state.section==='diagnostic')return diagnosticView();if(sectionType[state.section])return recordView();return moreView()}
function cashflowView(){const b=records.business||{};const rows=[...(b.collection||[]).map((x,i)=>({...x,_type:'collection',_i:i,_label:'Cobro'})),...(b.cashPayment||[]).map((x,i)=>({...x,_type:'cashPayment',_i:i,_label:'Pago'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||''));return `<div class="sectionHead"><div><h2>Flujo de caja</h2><p>Registra dinero realmente cobrado o pagado. No se confunde con ventas ni gastos devengados.</p></div><div style="display:flex;gap:8px"><button class="primary cashAdd" data-cash="collection">＋ Cobro</button><button class="ghost cashAdd" data-cash="cashPayment">− Pago</button></div></div><div class="card"><div class="list">${rows.length?rows.map(x=>`<div class="row"><div class="ico">${x._label==='Cobro'?'＋':'−'}</div><div><b>${x.name}</b><small>${x.date} · ${x._label} · ${x.demo?'Demostración':'Real'}</small></div><div class="amount">${x._label==='Cobro'?'+':'−'}${moneyMinor(asMinor(x),currency())} <button class="ghost deleteCash" data-type="${x._type}" data-i="${x._i}">×</button></div></div>`).join(''):'<p class="sub">Todavía no hay cobros ni pagos reales registrados.</p>'}</div></div>`}
function resultsView(){const m=businessMonth(businessEngineData(),monthKey());return `<div class="sectionHead"><div><h2>Resultado</h2><p>Resultado económico del mes; no equivale al efectivo disponible.</p></div></div><div class="kpis"><div class="kpi"><small>Ventas</small><strong>${moneyMinor(m.sales,currency())}</strong></div><div class="kpi"><small>Costos variables</small><strong>${moneyMinor(m.variableCosts,currency())}</strong></div><div class="kpi"><small>Gastos operativos</small><strong>${moneyMinor(m.operatingExpenses,currency())}</strong></div><div class="kpi"><small>Resultado</small><strong>${moneyMinor(m.operatingResult,currency())}</strong></div></div>`}
function diagnosticView(){const m=personalMonth(personalEngineData(),monthKey()),p=personalPosition(personalEngineData(),'2026-09-30');return `<div class="sectionHead"><div><h2>Diagnóstico financiero</h2><p>Lectura automática basada en tus registros del mes.</p></div></div><div class="grid"><div class="card"><h3>Liquidez mensual</h3><h2>${moneyMinor(m.available,currency())}</h2><p class="sub">${m.available>=0?'Disponible positivo después de compromisos registrados.':'Disponible negativo: las salidas registradas superan las entradas.'}</p></div><div class="card"><h3>Patrimonio</h3><h2>${moneyMinor(p.netWorth,currency())}</h2><p class="sub">Activos registrados menos saldos de deuda registrados.</p></div></div>`}
function openCashModal(type){const isIn=type==='collection';openModalForm(isIn?'Nuevo cobro':'Nuevo pago',`<div class="formGrid"><div class="field"><label>Concepto</label><input id="rName"></div><div class="field"><label>Monto (${currency()})</label><input id="rAmount" inputmode="decimal" placeholder="0.00"></div><div class="field"><label>Fecha</label><input id="rDate" type="date" value="2026-09-28"></div></div>`,()=>{const name=$('#rName').value.trim(),amountMinor=toMinor($('#rAmount').value);if(!name||amountMinor===null)return;const b=records.business||(records.business={});(b[type]||(b[type]=[])).push({name,amountMinor,currency:currency(),date:$('#rDate').value,demo:false});saveRecords();$('#modalWrap').classList.add('hidden');render()})}
function profile(){const initials=profileData.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();return `<div class="sectionHead"><div><h2>Mi perfil</h2><p>Identidad, país y monedas principales.</p></div><button class="primary" id="saveProfile">Guardar cambios</button></div><div class="grid"><div class="card"><div class="profileCard"><div class="profilePhoto" id="photoPreview" style="${profileData.photoUrl?`background-image:url(${profileData.photoUrl});background-size:cover;background-position:center;font-size:0`:''}">${initials}</div><div><h2 style="margin:0">${profileData.name}</h2><p class="sub">Cuenta principal</p><button class="ghost" id="changePhoto" style="margin-top:10px">Cambiar foto</button><input type="file" id="photoInput" accept="image/jpeg,image/png,image/webp" hidden></div></div></div><div class="card"><div class="formGrid"><div class="field"><label>Nombre</label><input id="pfName" value="${profileData.name}"></div><div class="field"><label>Correo</label><input id="pfEmail" value="${profileData.email}" disabled></div><div class="field"><label>País</label><select id="pfCountry">${['Ecuador','España','Estados Unidos','Colombia','México'].map(x=>`<option ${x===profileData.country?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Moneda personal</label><select id="pfPCurrency">${['USD','EUR','GBP','MXN','COP'].map(x=>`<option ${x===profileData.personalCurrency?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Moneda negocio</label><select id="pfBCurrency">${['USD','EUR','GBP','MXN','COP'].map(x=>`<option ${x===profileData.businessCurrency?'selected':''}>${x}</option>`).join('')}</select></div></div></div></div>`}
function demoActive(mode){return Object.values(records[mode]||{}).some(a=>(a||[]).some(x=>x.demo))}
function settings(){return `<div class="sectionHead"><div><h2>Ajustes</h2><p>Apariencia, sonido, seguridad y datos de demostración.</p></div></div><div class="grid"><div class="card"><h3>Apariencia y sonido</h3><div class="settingsRow"><div><b>Modo de color</b><small>Claro, oscuro o según tu dispositivo.</small></div><button class="ghost" id="settingTheme">${themeLabels[state.theme]||'Sistema'}</button></div><div class="settingsRow"><div><b>Sonido al cambiar de espacio</b><small>Un tono breve al pasar entre Personal y Negocio.</small></div><button class="ghost" id="settingSound">${state.sound?'Activado':'Silenciado'}</button></div><div class="settingsRow"><div><b>Recorrido inicial</b><small>Vuelve a ver el tutorial cuando quieras.</small></div><button class="ghost" id="restartTour">Ver recorrido</button></div></div><div class="card"><h3>Seguridad de la cuenta</h3><div class="settingsRow"><div><b>Cambiar contraseña</b><small>Mínimo 8 caracteres.</small></div><button class="ghost" id="changePassword">Cambiar</button></div><div class="settingsRow"><div><b>Exportar mis datos</b><small>Descarga una copia JSON de tus datos de cuenta y finanzas.</small></div><button class="ghost" id="exportData">Exportar</button></div><div class="settingsRow"><div><b>Eliminar cuenta</b><small>Elimina permanentemente tu cuenta y datos asociados.</small></div><button class="ghost" id="deleteAccount">Eliminar</button></div></div><div class="card"><h3>Datos de demostración</h3>${['personal','business'].map(m=>`<div class="settingsRow"><div><b>${m==='personal'?'Personal':'Negocio'}</b><small>${m==='personal'?'12 meses':'24 meses'} de ejemplo; nunca elimina datos reales.</small></div><button class="ghost demoToggle" data-demo="${m}">${demoActive(m)?'Eliminar demo':'Cargar demo'}</button></div>`).join('')}</div></div>`}
function openRecordModal(){const type=sectionType[state.section];openModalForm(`Nuevo ${titles[state.section].toLowerCase()}`,`<div class="formGrid"><div class="field"><label>Nombre / concepto</label><input id="rName" placeholder="Ej. Salario"></div><div class="field"><label>Monto (${currency()})</label><input id="rAmount" type="number" min="0" step="0.01" placeholder="0.00"></div><div class="field"><label>Fecha</label><input id="rDate" type="date" value="2026-09-28"></div></div>`,()=>{const name=$('#rName').value.trim(),amountMinor=toMinor($('#rAmount').value);if(!name||amountMinor===null)return;listFor(type).push({name,amountMinor,currency:currency(),date:$('#rDate').value,demo:false});saveRecords();$('#modalWrap').classList.add('hidden');render()})}
function openModalForm(title,body,onSave){$('#modal').innerHTML=`<button class="ghost modalClose">×</button><h2>${title}</h2>${body}<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px"><button class="ghost modalCancel">Cancelar</button><button class="primary modalSave">Guardar</button></div>`;$('#modalWrap').classList.remove('hidden');$('.modalClose').onclick=$('.modalCancel').onclick=()=>$('#modalWrap').classList.add('hidden');$('.modalSave').onclick=onSave}
function toggleDemo(mode){records[mode] ||= {}; if(demoActive(mode)){Object.keys(records[mode]).forEach(k=>records[mode][k]=(records[mode][k]||[]).filter(x=>!x.demo))}else{Object.entries(seed[mode]).forEach(([k,arr])=>{records[mode][k] ||= [];arr.forEach(([name,amount],i)=>records[mode][k].push({name,amountMinor:Math.round(amount*100),currency:mode==='personal'?profileData.personalCurrency:profileData.businessCurrency,date:`2026-09-${String(10+i).padStart(2,'0')}`,demo:true}))})}saveRecords();render()}
function bindExtras(){$$('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info));$$('[data-sim]').forEach(b=>b.onclick=()=>showSim(b.dataset.sim));$$('[data-personal-decision]').forEach(b=>b.onclick=()=>showPersonalDecision(b.dataset.personalDecision));$('#restartTour')?.addEventListener('click',()=>startTour(true));$('#settingTheme')?.addEventListener('click',cycleTheme);$('#settingSound')?.addEventListener('click',()=>{setSound(!state.sound);render()});$('#newRecord')?.addEventListener('click',openRecordModal);$$('.cashAdd').forEach(b=>b.onclick=()=>openCashModal(b.dataset.cash));$$('.deleteCash').forEach(b=>b.onclick=()=>{(records.business[b.dataset.type]||[]).splice(Number(b.dataset.i),1);saveRecords();render()});$$('.deleteRecord').forEach(b=>b.onclick=()=>{listFor(sectionType[state.section]).splice(Number(b.dataset.i),1);saveRecords();render()});$$('.demoToggle').forEach(b=>b.onclick=()=>toggleDemo(b.dataset.demo));$('#changePhoto')?.addEventListener('click',()=>$('#photoInput').click());$('#photoInput')?.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{profileData.photo=await cloud.uploadAvatar(f);profileData.photoUrl=await cloud.avatarObjectUrl(profileData.photo);await cloud.saveProfile(profileData);render()}catch(err){alert(err.message)}});$('#saveProfile')?.addEventListener('click',async()=>{profileData={...profileData,name:$('#pfName').value.trim()||profileData.name,country:$('#pfCountry').value,personalCurrency:$('#pfPCurrency').value,businessCurrency:$('#pfBCurrency').value};try{await cloud.saveProfile(profileData);render()}catch(e){showCloudError(e)}});$('#exportData')?.addEventListener('click',async()=>{try{const data=await cloud.exportMyData();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`finanzas-en-orden-datos-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){alert(e.message)}});$('#changePassword')?.addEventListener('click',()=>openModalForm('Cambiar contraseña','<div class="field"><label>Nueva contraseña</label><input id="newPassword" type="password" minlength="8" autocomplete="new-password"></div>',async()=>{try{await cloud.changePassword($('#newPassword').value);$('#modalWrap').classList.add('hidden');alert('Contraseña actualizada.')}catch(e){alert(e.message)}}));$('#deleteAccount')?.addEventListener('click',()=>openModalForm('Eliminar cuenta','<p>Esta acción es permanente. Escribe <b>ELIMINAR</b> para confirmar.</p><div class="field"><input id="deleteConfirm" autocomplete="off" placeholder="ELIMINAR"></div>',async()=>{if($('#deleteConfirm').value!=='ELIMINAR'){alert('Escribe ELIMINAR para confirmar.');return}try{await cloud.deleteMyAccount();location.reload()}catch(e){alert(e.message)}}))}
const onboardingCopy={personal:[['Paso 1 de 3','Registra tu punto de partida','Añade primero tus ingresos y tus gastos habituales. No necesitas completar todo en un día.','Ingresos → Gastos'],['Paso 2 de 3','Completa tus compromisos','Después registra deudas, ahorro y metas. Así el sistema entiende lo que ya está comprometido.','Deudas → Ahorro → Metas'],['Paso 3 de 3','Mira una sola prioridad','Vuelve a Inicio. Revisa tu situación financiera y abre la recomendación principal antes de tomar otra decisión.','Inicio → Decisiones']],business:[['Paso 1 de 3','Registra la operación','Empieza por ventas, costos y gastos. Esto construye el resultado económico del negocio.','Ventas → Costos → Gastos'],['Paso 2 de 3','Registra la caja real','Añade cobros y pagos reales. Una venta no es lo mismo que dinero cobrado.','Cobros → Pagos'],['Paso 3 de 3','Decide con contexto','Revisa punto de equilibrio y después prueba escenarios en Decisiones antes de actuar.','Plan → Decisiones']]};
function showOnboarding(){state.onboardingStep=0;state.onboardingChoice='personal';state.onboardingMode='personal';$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');$('#onboardingGate').classList.remove('hidden');paintOnboarding()}
function onboardingModes(){return state.onboardingChoice==='both'?['personal','business']:[state.onboardingChoice]}
function paintOnboarding(){const box=$('#onboardingContent'),track=$('#onboardingTrack');if(state.onboardingStep===0){track.innerHTML='<span class="active">1</span><i></i><span>2</span><i></i><span>3</span>';box.innerHTML=`<div class="onboardingCard"><span class="eyebrow">ANTES DE EMPEZAR</span><h1>¿Qué quieres organizar primero?</h1><p>Puedes usar Personal, Negocio o ambos. Nunca mezclaremos sus datos.</p><div class="choiceGrid"><button class="choiceCard active" data-onboard-choice="personal"><span>○</span><b>Mis finanzas personales</b><small>Ingresos, gastos, deudas, ahorro y metas.</small></button><button class="choiceCard" data-onboard-choice="business"><span>▣</span><b>Mi negocio</b><small>Ventas, costos, caja y punto de equilibrio.</small></button><button class="choiceCard" data-onboard-choice="both"><span>◇</span><b>Configurar ambos</b><small>Te mostramos 3 pasos para cada espacio.</small></button></div><button class="primary onboardingNext">Continuar →</button></div>`;$$('[data-onboard-choice]').forEach(b=>b.onclick=()=>{state.onboardingChoice=b.dataset.onboardChoice;$$('[data-onboard-choice]').forEach(x=>x.classList.toggle('active',x===b))});$('.onboardingNext').onclick=()=>{state.onboardingMode=onboardingModes()[0];state.onboardingStep=1;paintOnboarding()};return}const modes=onboardingModes(), modeIndex=modes.indexOf(state.onboardingMode), steps=onboardingCopy[state.onboardingMode], stepIndex=((state.onboardingStep-1)%3), [label,title,copy,path]=steps[stepIndex];track.innerHTML=`<span class="${stepIndex>=0?'active':''}">1</span><i class="${stepIndex>=1?'active':''}"></i><span class="${stepIndex>=1?'active':''}">2</span><i class="${stepIndex>=2?'active':''}"></i><span class="${stepIndex>=2?'active':''}">3</span>`;box.innerHTML=`<div class="onboardingCard"><div class="onboardingModeTag">${state.onboardingMode==='personal'?'Personal':'Negocio'} · ${label}</div><h1>${title}</h1><p>${copy}</p><div class="onboardingPath">${path.split(' → ').map((x,i)=>`<span>${i+1}</span><b>${x}</b>`).join('<i>→</i>')}</div><div class="onboardingActions"><button class="ghost onboardingBack">Atrás</button><button class="primary onboardingNext">${stepIndex===2&&modeIndex===modes.length-1?'Entrar a la aplicación →':'Siguiente →'}</button></div></div>`;$('.onboardingBack').onclick=()=>{if(stepIndex===0){state.onboardingStep=0;paintOnboarding()}else{state.onboardingStep--;paintOnboarding()}};$('.onboardingNext').onclick=async()=>{if(stepIndex<2){state.onboardingStep++;paintOnboarding();return}if(modeIndex<modes.length-1){state.onboardingMode=modes[modeIndex+1];state.onboardingStep=1;paintOnboarding();return}profileData.tutorialCompleted=false;state.mode=modes[0];localStorage.setItem('feo-mode',state.mode);$('#onboardingGate').classList.add('hidden');$('#shell').classList.remove('hidden');$('#mobileNav').classList.remove('hidden');render();setTimeout(()=>startTour(true),250)}}

function hideEntryGates(){['checkoutGate','authGate','paidSignupGate','accessGate'].forEach(id=>$('#'+id)?.classList.add('hidden'))}
function showCheckout(message=''){hideEntryGates();$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');$('#checkoutGate').classList.remove('hidden');if(message)$('#checkoutMsg').textContent=message}
function showExistingLogin(message=''){hideEntryGates();showAuth(message)}
function showPaidSignup(email,claim){hideEntryGates();$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');$('#paidSignupGate').classList.remove('hidden');$('#paidEmail').value=email;sessionStorage.setItem('feo-paid-claim',claim);sessionStorage.setItem('feo-paid-email',email)}
async function boot(){
 const authType=cloud.acceptAuthFromUrl();
 const qp=new URLSearchParams(location.search);
 if(qp.get('checkout')==='cancelled'){history.replaceState(null,'',location.pathname);showCheckout('El pago fue cancelado. No se creó ninguna cuenta.');return}
 if(qp.get('checkout')==='approved'&&qp.get('cid')&&qp.get('cs')&&qp.get('token')){
   hideEntryGates();$('#checkoutGate').classList.remove('hidden');$('#checkoutMsg').textContent='Confirmando tu pago…';
   try{
     const r=await cloud.capturePublicCheckout(qp.get('cid'),qp.get('cs'),qp.get('token'));
     history.replaceState(null,'',location.pathname);
     showPaidSignup(r.email,r.claim_token);
   }catch(e){
     history.replaceState(null,'',location.pathname);
     showCheckout('No pudimos confirmar el pago: '+e.message);
   }
   return;
 }
 const pendingClaim=sessionStorage.getItem('feo-paid-claim'), pendingEmail=sessionStorage.getItem('feo-paid-email');
 if(pendingClaim&&pendingEmail){showPaidSignup(pendingEmail,pendingClaim);return}
 const user=await cloud.currentUser();
 if(user){await enterApp();if(authType==='recovery'){state.section='settings';render();setTimeout(()=>$('#changePassword')?.click(),100)};return}
 showCheckout();
}
async function enterApp(){try{const lic=await cloud.myLicense();adminMode=await cloud.isAdmin();if(!adminMode&&lic?.status!=='active'){showAccessPending(lic);return}hideEntryGates();const data=await cloud.loadData();records=data.records;profileData={...PROFILE_DEFAULT,...data.profile};if(profileData.theme&&['light','dark','system'].includes(profileData.theme))state.theme=profileData.theme;localStorage.setItem('feo-theme',state.theme);applyTheme();profileData.photoUrl=await cloud.avatarObjectUrl(profileData.photo);$('#authGate')?.classList.add('hidden');$('#accessGate')?.classList.add('hidden');if(adminMode){$('#shell').classList.remove('hidden');$('#mobileNav').classList.remove('hidden');injectAdminButton();render();return}if(!profileData.tutorialCompleted){showOnboarding();return}$('#shell').classList.remove('hidden');$('#mobileNav').classList.remove('hidden');render()}catch(e){showAuth(e.message)}}
function showAccessPending(lic,message=''){ hideEntryGates();$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');const g=$('#accessGate');g?.classList.remove('hidden');const st=$('#accessStatus');if(st)st.textContent=message||(lic?`Estado de acceso: ${lic.status}.`:'Esta cuenta no tiene una compra asociada.');const buy=$('#buyAccess');if(buy){buy.textContent='Comprar acceso · USD 29 →';buy.onclick=()=>{cloud.signOut();showCheckout('Completa el pago primero. Después podrás entrar con tu cuenta.')}}const refresh=$('#refreshAccess');if(refresh)refresh.onclick=async()=>{refresh.disabled=true;try{const pendingClaim=sessionStorage.getItem('feo-paid-claim');if(pendingClaim){await cloud.claimPaidAccess(pendingClaim);sessionStorage.removeItem('feo-paid-claim');sessionStorage.removeItem('feo-paid-email');await enterApp();return}const l=await cloud.myLicense();if(l?.status==='active'){await enterApp();return}st.textContent='No encontramos una compra confirmada asociada a esta cuenta.'}catch(e){st.textContent=e.message}finally{refresh.disabled=false}}}
function injectAdminButton(){const b=document.createElement('button');b.id='adminOpen';b.innerHTML='▦ <span>Admin</span>';b.onclick=()=>openAdmin();document.querySelector('.sideBottom')?.prepend(b)}
async function openAdmin(){
 try{
  const d=await cloud.adminDashboard();
  const rows=(d.users||[]).map(u=>{
   const l=u.license, pay=u.last_payment;
   const payText=pay?`${esc(pay.status)} · ${esc(pay.currency)} ${(Number(pay.amount_minor)/100).toFixed(2)}`:'Sin pago registrado';
   const action=l?`<button class="ghost adminLicense" data-user="${u.id}" data-status="${l.status==='active'?'revoked':'active'}">${l.status==='active'?'Desactivar':'Activar'}</button>`:'—';
   return `<div class="adminRow"><div><b>${esc(u.full_name||u.email||'Usuario')}</b><small>${esc(u.country||'—')} · ${esc(u.email||'Sin correo')}</small></div><div><b>${esc(l?.status||'sin licencia')}</b><small>${payText}</small></div><div>${action}</div><div><button class="ghost adminNote" data-user="${u.id}">Nota</button></div></div>`;
  }).join('');
  $('#content').innerHTML=`<div class="sectionHead"><div><h2>Administración</h2><p>Acceso, pagos y soporte. Los movimientos financieros no están disponibles aquí.</p></div></div><div class="card"><div class="adminTable">${rows||'<p class="sub">Aún no hay usuarios.</p>'}</div></div>`;
  $$('.adminLicense').forEach(b=>b.onclick=async()=>{try{await cloud.adminSetLicense(b.dataset.user,b.dataset.status);await openAdmin()}catch(e){alert(e.message)}});
  $$('.adminNote').forEach(b=>b.onclick=()=>openModalForm('Nota de soporte','<div class="field"><label>Nota interna</label><textarea id="supportNote" maxlength="1000"></textarea></div>',async()=>{await cloud.adminAddNote(b.dataset.user,$('#supportNote').value);$('#modalWrap').classList.add('hidden')}));
 }catch(e){alert(e.message)}
}

function showAuth(message=''){const gate=$('#authGate');gate?.classList.remove('hidden');$('#shell').classList.add('hidden');$('#mobileNav').classList.add('hidden');if(message&&$('#authMsg'))$('#authMsg').textContent=message}
function authMessage(error){const m=String(error?.message||error||'').toLowerCase();if(m.includes('anonymous sign-ins are disabled'))return 'Escribe tu correo electrónico para crear la cuenta.';if(m.includes('invalid login credentials'))return 'Correo o contraseña incorrectos.';if(m.includes('email not confirmed'))return 'Confirma tu correo antes de iniciar sesión.';if(m.includes('user already registered'))return 'Ya existe una cuenta con ese correo. Inicia sesión.';if(m.includes('password'))return 'La contraseña debe tener al menos 8 caracteres.';if(m.includes('email'))return 'Revisa que el correo electrónico sea válido.';return 'No pudimos completar la solicitud. Inténtalo nuevamente.'}
function validateAuth(mode){const email=$('#authEmail').value.trim(),password=$('#authPassword').value,msg=$('#authMsg');msg.textContent='';if(!email){msg.textContent='Escribe tu correo electrónico.';$('#authEmail').focus();return null}if(!email.includes('@')||email.startsWith('@')||!email.slice(email.indexOf('@')+1).includes('.')||email.endsWith('.')){msg.textContent='Escribe un correo electrónico válido.';$('#authEmail').focus();return null}if(!password){msg.textContent='Escribe tu contraseña.';$('#authPassword').focus();return null}if(password.length<8){msg.textContent='La contraseña debe tener al menos 8 caracteres.';$('#authPassword').focus();return null}return {email,password,msg}}
window.feoAuth={async forgot(){const email=$('#authEmail').value.trim(),msg=$('#authMsg');msg.textContent='';if(!email||!email.includes('@')||email.startsWith('@')||!email.slice(email.indexOf('@')+1).includes('.')||email.endsWith('.')){msg.textContent='Escribe un correo electrónico válido.';$('#authEmail').focus();return}try{await cloud.requestPasswordReset(email);msg.textContent='Si existe una cuenta con ese correo, recibirás instrucciones para restablecer la contraseña.'}catch(e){msg.textContent=authMessage(e)}},async submit(mode){const v=validateAuth(mode);if(!v)return;const {email,password,msg}=v;const btn=$('#authSignin');const original=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Ingresando…'}try{await cloud.signIn(email,password);const pendingClaim=sessionStorage.getItem('feo-paid-claim');if(pendingClaim){await cloud.claimPaidAccess(pendingClaim);sessionStorage.removeItem('feo-paid-claim');sessionStorage.removeItem('feo-paid-email')}await enterApp()}catch(e){msg.textContent=authMessage(e)}finally{if(btn){btn.disabled=false;btn.textContent=original}}},logout(){cloud.signOut();location.reload()}};
let authMode='signin';
function setAuthMode(mode){
  authMode=mode;
  const signup=mode==='signup';
  $('#authKicker').textContent=signup?'CREAR CUENTA':'BIENVENIDO';
  $('#authTitle').textContent=signup?'Crea tu cuenta':'Accede a tus finanzas';
  $('#authCopy').textContent=signup?'Usa tu correo y una contraseña segura para comenzar.':'Tu situación financiera, organizada para que sepas qué hacer después.';
  $('#signupConfirmWrap').classList.toggle('hidden',!signup);
  $('#forgotPassword').classList.toggle('hidden',signup);
  $('#authSignin').innerHTML=signup?'Crear mi cuenta <span>→</span>':'Iniciar sesión <span>→</span>';
  $('#authSignup').textContent=signup?'Ya tengo una cuenta':'Crear una cuenta';
  $('#authPassword').setAttribute('autocomplete',signup?'new-password':'current-password');
  $('#authMsg').textContent='';
}
function showSignupSuccess(email){
  $('#authEmail').closest('.authCard').querySelectorAll('label,input,#authSignin,#authSignup,#forgotPassword,#authMsg').forEach(el=>el.classList.add('hidden'));
  $('#authKicker').textContent='REVISA TU CORREO';
  $('#authTitle').textContent='Confirma tu cuenta';
  $('#authCopy').textContent='Hemos enviado un enlace de confirmación a '+email+'.';
  $('#signupSuccess').classList.remove('hidden');
}

let paypalEmbeddedReady=false;
let paypalCardFields=null;
let paypalCheckoutContext=null;
async function loadPayPalSdkV5(){
  if(window.paypal?.CardFields)return;
  const cfg=await cloud.paypalPublicConfig();
  await new Promise((resolve,reject)=>{
    const existing=document.querySelector('script[data-paypal-v5]');
    if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}
    const sc=document.createElement('script');
    const host=cfg.environment==='sandbox'?'https://www.sandbox.paypal.com':'https://www.paypal.com';
    sc.src=host+'/sdk/js?client-id='+encodeURIComponent(cfg.clientId)+'&currency=USD&components=buttons,card-fields';
    sc.async=true;sc.dataset.paypalV5='1';
    sc.onload=resolve;sc.onerror=()=>reject(new Error('No se pudo cargar el checkout seguro de PayPal.'));
    document.head.appendChild(sc);
  });
}
async function createEmbeddedOrder(){
  const email=$('#checkoutEmail').value.trim().toLowerCase(),msg=$('#checkoutMsg');
  msg.textContent='';
  if(!email||!email.includes('@')||!(email.split('@')[1]||'').includes('.')){msg.textContent='Escribe un correo electrónico válido.';throw new Error('INVALID_EMAIL')}
  const o=await cloud.createPublicCheckout(email);
  paypalCheckoutContext=o;
  return o.order_id;
}
async function approveEmbeddedOrder(data){
  if(!paypalCheckoutContext)throw new Error('No encontramos el checkout activo.');
  const c=await cloud.capturePublicCheckout(paypalCheckoutContext.checkout_id,paypalCheckoutContext.checkout_secret,data.orderID);
  if(!c?.claim_token)throw new Error('El pago se realizó, pero no pudimos preparar el acceso.');
  showPaidSignup(c.email,c.claim_token);
}
async function initEmbeddedPayPal(){
  if(paypalEmbeddedReady)return;
  const loading=$('#paypalCardLoading'),fields=$('#paypalCardFields'),unavailable=$('#paypalCardUnavailable'),msg=$('#checkoutMsg');
  try{
    loading?.classList.remove('hidden');unavailable?.classList.add('hidden');
    await loadPayPalSdkV5();
    paypalCardFields=window.paypal.CardFields({
      createOrder:createEmbeddedOrder,
      onApprove:approveEmbeddedOrder,
      onError:(err)=>{if(msg)msg.textContent='No pudimos procesar la tarjeta. Revisa los datos o usa PayPal.'}
    });
    if(!paypalCardFields?.isEligible()){document.querySelector('.embeddedPay')?.classList.add('hidden');document.querySelector('.payDivider')?.classList.add('hidden');throw new Error('CARD_FIELDS_NOT_ELIGIBLE')}
    await paypalCardFields.NumberField({style:{input:{'font-size':'16px','font-family':'Arial, sans-serif',color:'#102927'}}}).render('#paypal-card-number');
    await paypalCardFields.ExpiryField({style:{input:{'font-size':'16px','font-family':'Arial, sans-serif',color:'#102927'}}}).render('#paypal-card-expiry');
    await paypalCardFields.CVVField({style:{input:{'font-size':'16px','font-family':'Arial, sans-serif',color:'#102927'}}}).render('#paypal-card-cvv');
    fields?.classList.remove('hidden');loading?.classList.add('hidden');paypalEmbeddedReady=true;
  }catch(e){
    loading?.classList.add('hidden');unavailable?.classList.remove('hidden');
    if(msg&&String(e?.message||e)!=='CARD_FIELDS_NOT_ELIGIBLE')msg.textContent='No pudimos preparar el pago seguro. Inténtalo nuevamente.';
  }
}
async function payEmbeddedCard(){
  const msg=$('#checkoutMsg'),btn=$('#payWithCard');msg.textContent='';
  if(!paypalCardFields){msg.textContent='El pago con tarjeta todavía se está preparando.';return}
  btn.disabled=true;const old=btn.textContent;btn.textContent='Procesando pago…';
  try{await paypalCardFields.submit()}
  catch(e){msg.textContent='No pudimos procesar la tarjeta. Revisa los datos e inténtalo otra vez.'}
  finally{btn.disabled=false;btn.textContent=old}
}
function bindAuthActions(){
  $('#payWithCard')?.addEventListener('click',payEmbeddedCard);
  initEmbeddedPayPal();
  $('#startCheckout')?.addEventListener('click',async()=>{
    const email=$('#checkoutEmail').value.trim().toLowerCase(),msg=$('#checkoutMsg'),btn=$('#startCheckout');
    msg.textContent='';
    if(!email||!email.includes('@')||!(email.split('@')[1]||'').includes('.')){msg.textContent='Escribe un correo electrónico válido.';return}
    btn.disabled=true;const old=btn.textContent;btn.textContent='Abriendo PayPal…';
    try{const o=await cloud.createPublicCheckout(email);if(!o?.approve_url)throw new Error('PayPal no devolvió el enlace de pago.');location.assign(o.approve_url)}
    catch(e){msg.textContent=e.message;btn.disabled=false;btn.textContent=old}
  });
  $('#existingLogin')?.addEventListener('click',()=>showExistingLogin());
  $('#paidExistingLogin')?.addEventListener('click',()=>showExistingLogin());
  $('#createPaidAccount')?.addEventListener('click',async()=>{
    const name=$('#paidName').value.trim(),email=$('#paidEmail').value.trim().toLowerCase(),password=$('#paidPassword').value,confirm=$('#paidPasswordConfirm').value,msg=$('#paidSignupMsg'),btn=$('#createPaidAccount'),claim=sessionStorage.getItem('feo-paid-claim');
    msg.textContent='';
    if(name.length<2){msg.textContent='Escribe tu nombre.';$('#paidName').focus();return}
    if(password.length<8){msg.textContent='La contraseña debe tener al menos 8 caracteres.';return}
    if(password!==confirm){msg.textContent='Las contraseñas no coinciden.';return}
    if(!claim){msg.textContent='El comprobante de pago ya no está disponible. Contacta soporte con tu recibo de PayPal.';return}
    btn.disabled=true;const old=btn.textContent;btn.textContent='Creando tu acceso…';
    try{
      await cloud.createPaidAccount(email,password,claim);
      await cloud.signIn(email,password);
      await cloud.saveProfile({name,country:'Ecuador',personalCurrency:'USD',businessCurrency:'USD',theme:'system',tutorialCompleted:false});
      sessionStorage.removeItem('feo-paid-claim');sessionStorage.removeItem('feo-paid-email');
      await enterApp();
    }catch(e){
      if(e.message==='ACCOUNT_EXISTS'){
        const email=$('#paidEmail').value.trim().toLowerCase();
        showExistingLogin('Ya tienes una cuenta. Inicia sesión para activar automáticamente esta compra.');
        $('#authEmail').value=email;
        $('#authEmail').readOnly=true;
        $('#authPassword').focus();
      }else{
        msg.textContent=e.message;
      }
      btn.disabled=false;btn.textContent=old;
    }
  });
  $('#authSignin')?.addEventListener('click',()=>window.feoAuth.submit('signin'));
  $('#authSignup')?.addEventListener('click',()=>showCheckout());
  $('#forgotPassword')?.addEventListener('click',()=>window.feoAuth.forgot());
  $('#accessLogout')?.addEventListener('click',()=>window.feoAuth.logout());
  $('#backToLogin')?.addEventListener('click',()=>location.reload());
  $('#resendConfirmation')?.addEventListener('click',async()=>{
    const btn=$('#resendConfirmation'), msg=$('#resendMsg'), email=$('#authCopy').textContent.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)?.[0]||$('#authEmail').value.trim();
    btn.disabled=true; const old=btn.textContent; btn.textContent='Enviando…'; msg.textContent='';
    try{await cloud.resendSignupConfirmation(email);msg.textContent='Correo reenviado. Usa el enlace más reciente.'}catch(e){msg.textContent=authMessage(e)}finally{btn.disabled=false;btn.textContent=old}
  });
}
bindAuthActions();
boot();
